### ISSUE TITLE
Add local_file_share to "Clones and Similar Projects"

### ISSUE THREAD

**Issue by woshimanong1990** [claudiodangelis/qrcp#100]
😀
I have write a python version。If you need,[ https://github.com/woshimanong1990/local_file_share](https://github.com/woshimanong1990/local_file_share)

**Comment by jeverling** [comment]
Hey @woshimanong1990, your link is broken. The text is correct but it refers to a non-existing page in this repo.

**Comment by claudiodangelis** [comment]
@woshimanong1990 thanks for this! I will add it to the README.

@jeverling thanks for spotting, I fixed the URL for @woshimanong1990

**Comment by claudiodangelis** [comment]
@woshimanong1990 , I added the project to the list of clones and similar projects in the README. If your project was inspired by mine, I would appreciate a mention on your README as well.

Thank you!
