### ISSUE TITLE
Add support for sending text to phone

### ISSUE THREAD

**Issue by PauloRSF** [claudiodangelis/qrcp#102]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

I think it would be cool to be able to send text from my pc to my phone directly. QRCP wouldn't even need to start the server, just render the qr code with the text.

**Comment by claudiodangelis** [comment]
Hello @PauloRSF, thanks for this proposal, though I consider it to be outside of the purpose of qrcp, since it can be achieved with a regular qr encoding app. Thanks for understanding!
