### ISSUE TITLE
windows installation issue

### ISSUE THREAD

**Issue by Ipassanti** [claudiodangelis/qrcp#104]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [Y] I have a question
- [ ] Other

I'm really sorry to submit this issue for asking easy question. But I really have difficult to install QRCP on Windows. 
I have downloaded Go Lang and use  "go get ~/qrcp" cmd. But i can't find Chmod Command on Windows.
And there's no ".exe" file in the released package. 
Can you add a windows version  installation guide?
Really thanks for that.

**Comment by claudiodangelis** [comment]
Hello, the "chmod" command is a Linux and Mac command, sorry if I did not make it clear in the README.

Have you tried running:

```sh
go get github.com/claudiodangelis/qrcp
```

If you are new to go, please make sure you have read the installation manual for Windows: https://golang.org/doc/install#windows

After running the command above, you should be able to use the tool by simply running `qrcp` in the command prompt.

**Comment by Ipassanti** [comment]
yes,I had used the "go get" command to install the "qrcp".
But somehow the system cant find "qrcp" program.
In this picture, it said 'qrcp' is not a inner or outter command or executable  program.
But i don't know which step i havn't  done. 


<img width="675" alt="issue" src="https://user-images.githubusercontent.com/33710797/80208634-378b9400-8663-11ea-82b9-80a73f05a1de.PNG">

**Comment by claudiodangelis** [comment]
Thank you, just as a test, does it work if you run:

```sh
go\bin\qrcp
```

**Comment by Ipassanti** [comment]
Yup！
Thanks for spending time to solve  my problem ！ ：D

**Comment by claudiodangelis** [comment]
Please make sure to setup Go environment variables correctly, so that you don't have to use the full path of the binary every time.

**Comment by GokulNC** [comment]
@claudiodangelis 
I'm getting this error in Windows:

```
C:\Users\Name\Desktop>go get github.com/claudiodangelis/qrcp
..\go\src\github.com\claudiodangelis\qrcp\util\util.go:15:2: no Go files in C:\Users\Name\go\src\github.com\jhoonb\archivex
```

**Comment by claudiodangelis** [comment]
> @claudiodangelis
> I'm getting this error in Windows:
> 
> ```
> C:\Users\Name\Desktop>go get github.com/claudiodangelis/qrcp
> ..\go\src\github.com\claudiodangelis\qrcp\util\util.go:15:2: no Go files in C:\Users\Name\go\src\github.com\jhoonb\archivex
> ```

Which version of go are you using?

**Comment by GokulNC** [comment]
@claudiodangelis
I'm on `go version go1.14.2 windows/amd64`

**Comment by claudiodangelis** [comment]
Can you please try

```sh
go get -u github.com/claudiodangelis/qrcp
```

**Comment by GokulNC** [comment]
I'm getting the same error:
```
C:\Users\Name\Desktop>go get -u github.com/claudiodangelis/qrcp
..\go\src\github.com\claudiodangelis\qrcp\util\util.go:15:2: no Go files in C:\Users\Name\go\src\github.com\jhoonb\archivex
```

**Comment by claudiodangelis** [comment]
Could you please try this

```sh
go get github.com/jhoonb/archivex
```

then

```sh
go get github.com/claudiodangelis/qrcp
```

Thanks

**Comment by GokulNC** [comment]
I deleted my `C:\Users\Name\go\src\` directory (as mentioned [here](https://github.com/ponzu-cms/ponzu/issues/204#issuecomment-408116252)) and tried installing again, it worked!

Probably that directory was corrupt in my case, sorry for the trouble; I'm new to Go.
Please close the issue.

**Comment by claudiodangelis** [comment]
I'm glad to hear you figured it out, cheers!

**Comment by 30rus** [comment]
- @claudiodangelis ext install claudiodangelis.dun-theme
