### ISSUE TITLE
Logo is too big on README

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/qrcp#109]
Logo should not take all that space on the README.

**Comment by MrHeer** [comment]
Do you think this is okay？
![image](https://user-images.githubusercontent.com/18595761/81032286-d749ed00-8ec1-11ea-9506-6794c6409cd2.png)

**Comment by SuperSandro2000** [comment]
I would move it to the right with some css

**Comment by claudiodangelis** [comment]
Hello @MrHeer, @SuperSandro2000, thanks for proposing. I would just resize the logo by adjusting the `<svg>`'s sizing attributes that are currently set to: 

```
width="804.666px" height="306.14px" viewBox="0 0 804.666 306.14" e
nable-background="new 0 0 804.666 306.14
```

Half of the current values would be good enough I think.

**Comment by MrHeer** [comment]
Thank you. I'll try.

**Comment by MrHeer** [comment]
I feel much better after adjustment.
- Current:
![image](https://user-images.githubusercontent.com/18595761/81198876-8d155880-8ff4-11ea-9999-9b7f53be6eb5.png)
- After adjustment：
![image](https://user-images.githubusercontent.com/18595761/81199059-c3eb6e80-8ff4-11ea-92de-0729a5d68d4d.png)

**Comment by claudiodangelis** [comment]
Yea it looks much better now. Do you want to open a pull request? Many thanks for taking the time to adjust the size!

**Comment by MrHeer** [comment]
It's my honor.
