### ISSUE TITLE
电脑手机传输

### ISSUE THREAD

**Issue by coralinabubu** [claudiodangelis/qrcp#115]

**Comment by claudiodangelis** [comment]
Could you please explain in English? That would be very much appreciated , thank you.

**Comment by shisaq** [comment]
That title means "transferring data between PC and phone", which has no question, description or issue related... I think you could ignore and close it.

**Comment by claudiodangelis** [comment]
Thanks @shisaq, I have the same feeling, though I'll wait to hear from @coralinabubu for a few more days before closing it. I see they joined Github recently and might not be too much familiar with how it works yet.
