### ISSUE TITLE
Firewall Problem

### ISSUE THREAD

**Issue by Beegency** [claudiodangelis/qrcp#120]
I'm opening this issue because:

- [ ] I have a question
- My Go version is: go version go1.13.6 linux/amd64

I tried to send & receive files between a PC running CentOS7 and Android devices. Something went wrong when I scanned QR code and opened it in my phone's web browser. 

The error code seemed to imply that the address was unreachable. I checked the chosen interface and it was configured correctly. The request from my phone seemed to be blocked by the firewall.

**Comment by claudiodangelis** [comment]
Hello @Beegency, there might be two things that are preventing it from working:
1. wrong network interface
    make sure that the send URL printed belongs to the same subnet of your Android, for example:
         
2. firewall

**Comment by claudiodangelis** [comment]
Hello @Beegency, to exclude it is a firewall problem you could do this:

1. Check what is your active zone
```sh
sudo firewall-cmd --get-active-zones
```
It will probably be "public".

2. Allow traffic on a specific port, let's say 8080 (replace "public" in case the previous step returned something different)
```sh
sudo firewall-cmd --zone=public --add-port=8080/tcp --permanent
```
3. Reload the firewall
```sh
sudo firewall-cmd --reload
```

4. Run qrcp on the port 8080
```sh
qrcp --port 8080 yourfile.pdf
```

Please let me know how it goes!

**Comment by Beegency** [comment]
> Hello @Beegency, to exclude it is a firewall problem you could do this:
> 
> 1. Check what is your active zone
> 
> ```shell
> sudo firewall-cmd --get-active-zones
> ```
> 
> It will probably be "public".
> 
> 1. Allow traffic on a specific port, let's say 8080 (replace "public" in case the previous step returned something different)
> 
> ```shell
> sudo firewall-cmd --zone=public --add-port=8080/tcp --permanent
> ```
> 
> 1. Reload the firewall
> 
> ```shell
> sudo firewall-cmd --reload
> ```
> 
> 1. Run qrcp on the port 8080
> 
> ```shell
> qrcp --port 8080 yourfile.pdf
> ```
> 
> Please let me know how it goes!

After I stopped the firewall service, my phone got the permission to access the URL, but it still can't download any file. The product model is Huawei M6. 
However, my laptop finished the transmission successfully. How can I trace the error of my Android devices.

**Comment by nogweii** [comment]
Another consideration for RedHat based distributions is SELinux denials. Is it enabled, if so there should be errors in the audit log.

**Comment by claudiodangelis** [comment]
Very good point @nogweii, maybe @Beegency you can try enabling it with:
```sh
sudo semanage port -a -t http_port_t -p tcp 8080
```

**Comment by claudiodangelis** [comment]
@Beegency I am closing this issue for now, if you are still running into issues please feel free to reopen it.
