### ISSUE TITLE
Create a homebrew package

### ISSUE THREAD

**Issue by jiri** [claudiodangelis/qrcp#122]
I'm opening this issue because:
- [x] I want to request a feature

It would be nice to be able to install qrcp using `brew install qrcp` which is the de-facto standard way of installing software on macOS.

**Comment by claudiodangelis** [comment]
Hi @jiri, many thanks for suggesting, definitely something we should have.

**Comment by claudiodangelis** [comment]
Note to self: GoReleaser it's the tool we're using to build and release artifacts and it supports the generation of brews: https://goreleaser.com/homebrew/

**Comment by zub** [comment]
I have written a pull request for homebrew, awaiting approval due to CI crashing due to home directory permissions.

**Comment by claudiodangelis** [comment]
Hi @zub, thanks for taking the time to build the formula.
At startup, qrcp will read and/or write a configuration file in the home directory of the user, and at this time there is no way to override that behavior. 
I can release a patch to allow an arbitrary configuration file, so you can choose to store it in a writable directory.
Could this work?

**Comment by zub** [comment]
Hi! I wrote a patch this morning, letting the user specify location. Probably a nice feature to have in any case. It's been a while since I wrote any go, so please do give it a sanity check. :)

**Comment by claudiodangelis** [comment]
Hello @zub, as per version [0.6.3](https://github.com/claudiodangelis/qrcp/releases/tag/0.6.3) you can now pass the `--config` file.

```sh
qrcp --config /path/to/writable/file.json
```

**Comment by zub** [comment]
Great. Hopefully it'll be merged soon.

**Comment by zub** [comment]
Fixed by homebrew/homebrew-core#54368.

**Comment by claudiodangelis** [comment]
Thanks for submitting this tool to homebrew @zub!
