### ISSUE TITLE
Recieve multiple files from mobile

### ISSUE THREAD

**Issue by puneethkanna** [claudiodangelis/qrcp#123]
I'm opening this issue because:

- [ ] I want to request a feature

- My Go version is: _go1.13.8 linux/amd64_

**Comment by claudiodangelis** [comment]
Hello @puneethkanna, could you please describe what is the feature you are requesting?

Thanks!

**Comment by puneethkanna** [comment]
I tried to receive multiple files from mobile, but it is not working, so we can add this feature.

**Comment by claudiodangelis** [comment]
It should work, did you choose multiple files from the upload page? When you click the "Browse" button you can select multiple files. If the files are correctly selected, this is what you will see:
![image](https://user-images.githubusercontent.com/941963/80858997-c1d48900-8c5d-11ea-9acd-9c5568c82b0d.png)

**Comment by puneethkanna** [comment]
Okay, got it. It is not working with Google Photos app, when I select from the app it says memory is too low
