### ISSUE TITLE
bad string for qrcp version

### ISSUE THREAD

**Issue by michal037** [claudiodangelis/qrcp#129]
I'm opening this issue because:

- [X] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: None
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: None

---
qrcp version: 0.6.1
version string doesn't match the release:

![b1](https://user-images.githubusercontent.com/7441419/80930104-60bdca00-8db1-11ea-8e6c-628af34bfc42.png)

**Comment by claudiodangelis** [comment]
This is fixed in version 0.6.2, thanks for reporting!
