### ISSUE TITLE
receiving multiple files is cumbersome

### ISSUE THREAD

**Issue by michal037** [claudiodangelis/qrcp#131]
I'm opening this issue because:

- [ ] I have found a bug
- [X] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: None
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: None

---

`qrcp -k reveive`

Receiving multiple files is cumbersome. I'm sending a file from my phone to my computer. After sending the file, the message 'done' appears. Everything is fine up to this point. At this point, I want to send another file. It would be nice if there was an 'Upload another file' button. Which just refreshes the page. Because, it looks like at the end while the program is still waiting for files.

Or do it in such a way as not to close the previous window, but print below the message 'sent'.

After uploading the files, the 'End of transfer' button could be useful. Which will finish the program on your computer from web.

Also on the computer the ability to type the 'exit' command, which will end its work in a nice way. And not by the example 'CTRL + C' shortcut.

**Comment by claudiodangelis** [comment]
After some thinking I decided not to implement this. You have the options of uploading multiple files anyway.
Thanks for suggesting!

**Comment by michal037** [comment]
You're right, but it's a little slower in my opinion.

What do you think about this?:

https://github.com/claudiodangelis/qrcp/blob/b2293923e8acc33563c19604949628895998122b/pages/pages.go#L223

After sending the file to the PC, send `Done page` as `Upload page` + popup with a message that the file has been successfully transferred

This would reduce the number of page refreshes for uploading multiple files when using the `qrpc -k receive` command.
