### ISSUE TITLE
error message duplication in argumentless program call

### ISSUE THREAD

**Issue by michal037** [claudiodangelis/qrcp#133]
I'm opening this issue because:

- [X] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: None
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: None

---
qrcp version: 0.6.1
Maybe just for argumentless program call, write only help? What do you think?

![fot1](https://user-images.githubusercontent.com/7441419/80932552-42ab9600-8dc0-11ea-8c42-fab985175609.png)

**Comment by claudiodangelis** [comment]
Hello @michal037, thanks for reporting these issues! I will take care of all of it in the next few days, cheers.

**Comment by claudiodangelis** [comment]
Fixed in 0.6.2 which will be released in a few days, thanks for reporting! 
See the related PR #142
