### ISSUE TITLE
QR code doddled too crude when screen scale resized

### ISSUE THREAD

**Issue by peter17ji** [claudiodangelis/qrcp#139]
I'm opening this issue because:

- [X] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other
0.6.1 Windows binary(no Go env), Win10 2004 19041.208,screen scale 150%. 
The QR code can't be recognized by usual QR code readers.
Wonder if can be fixed under current command-line version or can only be fixed in future GUI version.
![屏幕截图(2)](https://user-images.githubusercontent.com/29380055/81135451-d3ce6880-8f8a-11ea-9a69-1901f0c82ff1.png)

**Comment by claudiodangelis** [comment]
Hello, thanks for reporting. This issue is related to the font used in Windows terminal. Can you please use a monospace font and let me know if that works for you? 

Other people are reporting similar issues on Windows in this issue: https://github.com/claudiodangelis/qrcp/issues/95

**Comment by tideillusion** [comment]
I meet the same problem.
![image](https://user-images.githubusercontent.com/46561353/81525751-65a8ed80-935e-11ea-91ab-f8994d1a9c56.png)
Also Win 10, in Chinese language env.
Changing the font in terminal makes no difference.
