### ISSUE TITLE
QR code is unscannable

### ISSUE THREAD

**Issue by aint** [claudiodangelis/qrcp#150]
I'm opening this issue because:

- [x] I have found a bug - not sure
- [ ] I want to request a feature
- [x] I have a question
- [ ] Other

- My Go version is: `go version go1.14 darwin/amd64`
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: `/Users/aint/Projects/go
`

Hi there,

It looks like a QR code is unscanable. Please see a screenshot below:

![image](https://user-images.githubusercontent.com/3179252/81843881-f0543d00-9556-11ea-9151-53c4a28eca01.png)

I tried different fonts but it looks quite the same. Any idea how I can fix it?

**Comment by SuperSandro2000** [comment]
I could scan the image without problems with the help of https://github.com/markusfisch/BinaryEye .

Your theme is inverting the qr code. Can you try it again with a theme with black background?

**Comment by aint** [comment]
Yes, the QR code is perfect on a dark theme. Thanks for your help!

![image](https://user-images.githubusercontent.com/3179252/81845994-129b8a00-955a-11ea-8a8c-710405019a31.png)

Also, interesting why a QR code is inverted for a light theme. I'm using macOS terminal with a default theme.

**Comment by SuperSandro2000** [comment]
> Also, interesting why a QR code is inverted for a light theme.

Cause characters are black instead of white or you couldn't read them.

**Comment by SuperSandro2000** [comment]
@claudiodangelis maybe you should recommend BinaryEye as it is quiet good even with inverted colors or not great looking QR codes.

**Comment by claudiodangelis** [comment]
Hello everyone, just so you know, we just released a new version, `0.6.4`, which adds the `--browser` flag. With this flag set, the QR is also printed to a new tab of the default browser.

I will close this ticket for now.
Thanks,
C

**Comment by LY1806620741** [comment]
I get the same problem. My system is `win11 professional x64`, when i run `qrcp receive` in `powershell` or `cmd`, I get the different result. What happen about it?
<img width="563" alt="image" src="https://github.com/user-attachments/assets/1c5ef7ea-ba10-4ac2-8f2e-04c56bb5bf8b">

then I search issue then try `qrcp receive -r` in `cmd`, nothing better change.
<img width="637" alt="image" src="https://github.com/user-attachments/assets/d657d2ad-2c2c-40d2-bc59-ae0f58f41f95">
