### ISSUE TITLE
[Win/PS] Fails when the folder name contains space and ends with backslash

### ISSUE THREAD

**Issue by imba-tjd** [claudiodangelis/qrcp#152]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

Version: ` qrcp_0.6.2_Windows_x86_64.tar.gz`

1. Create a folder named `a a`.
2. Open Powershell.
3. type `qrcp '.\a a\'`.
4. You will get a wired `Error: CreateFile .\a a": The filename, directory name, or volume label syntax is incorrect.`
5. How do I find this? I created a new folder with the default name `New folder`, I opened PS and typed `qrcp N` and typed TAB, PS autocomplited it to `qrcp '.\New folder\'`.
6. `qrcp '.\a a'` and `qrcp 'a a'` works, so a file named `a a` works. `qrcp 'a a\'` fails.
7. When the folder name is `a`, all of `qrcp '.\a\'`, `qrcp 'a\'`, `qrcp '.\a'` work.
8. feel free to `won't fix`.

**Comment by claudiodangelis** [comment]
Hello, thanks for reporting! This will be fixed in the next release 0.6.3!

**Comment by claudiodangelis** [comment]
Update: this will be released in 0.6.4

**Comment by claudiodangelis** [comment]
Can you please paste the error returned?
Thanks,
C

**Comment by imba-tjd** [comment]
```
PS E:\> qrcp '.\a a\'
Error: CreateFile .\a a": The filename, directory name, or volume label syntax is incorrect.
Run `qrcp help` for help.
```

Important Note: that command works fine in pwsh 7.1.0-preview.4, and fails on 5.1.19041.1 which is the default version of PS in Win10 2004

**Comment by claudiodangelis** [comment]
@imba-tjd thanks for clarifying. Since it works on a more recent version than 5.1.19041.1, I will consider this issue not to be related to qrcp. Is it possible to update pwsh on PS? I am considering stating in the README that qrcp is not supported on legacy PowerShell versions.

Thanks

**Comment by imba-tjd** [comment]
For now pwsh must be installed manually and it works with legacy PS side by side, not the relationship between edgium and edge legacy.

**Comment by claudiodangelis** [comment]
OH, I just realized that PS stands for PowerShell! I'm not a Windows user and for some reason I was thinking that it was the name of a device (like PlayStation) :facepalm: 

Well, if you could take the time to test it on version 7.0.2, which appears to be the latest stable, and confirm it works, I could close this issue as it's related to a deprecated version of pwsh. I would really appreciate that!

https://github.com/PowerShell/PowerShell/releases/tag/v7.0.2

**Comment by claudiodangelis** [comment]
I tried version pwsh 7.0.2 and worked great on Arch Linux:
![image](https://user-images.githubusercontent.com/941963/86024614-7c4df580-ba2d-11ea-8a13-e903a26701d5.png)

I will close this issue now, many thanks for taking the time to report it and assist me debugging.

Cheers,
Claudio

**Comment by imba-tjd** [comment]
Well, I need to make some more clarification.

pwsh is indeed built on top of the legacy PS, and legacy PS is indeed won't get any functional improvements.
But I don't treat legacy PS as a "deprecated version of pwsh", and I don't think Microsoft would replace the built-in PowerShell 5.1 with the new pwsh, personally.

Backslash is the directory seperator in Win. Legacy PS also suppport slash, but the autocomplete (aka <kbd>TAB</kbd>) would get backslash.
For PS 5.1, `qrcp './a a/'` also works. 
![图片](https://user-images.githubusercontent.com/24759802/86071230-536f4400-bab1-11ea-956a-7b505a80d391.png)

Anyway this scenario is rare so I think `won't fix` is resonalble. If someone encounter the same issue in the future, this can be referenced.

**Comment by claudiodangelis** [comment]
Ok, now it's clear. Let's apply a `won't fix` label for future reference. 
Cheers!
