### ISSUE TITLE
Source code release is not checksummed

### ISSUE THREAD

**Issue by zub** [claudiodangelis/qrcp#155]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

The source tarball does not have a corresponsing checksum in checksums.txt. Please consider adding this. :)

**Comment by Calinou** [comment]
The source tarball and zipball are generated automatically by GitHub, which is probably why it's not in `checksums.txt`.

Note that GitHub does *not* guarantee that automatically generated source archives will keep the same checksums over time. If you want to ensure this, you have to pack a source release yourself and upload it.

**Comment by claudiodangelis** [comment]
I've done a quick research and I can confirm what stated by @Calinou.
Thanks to both for taking the time to report and comment, cheers,
