### ISSUE TITLE
Can't download with Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter

### ISSUE THREAD

**Issue by app4deepin** [claudiodangelis/qrcp#157]
I'm opening this issue because:

- [ X] I have found a bug

I try QRCP with my 2 computers on deepin linux on both. my computer have the same configuration. Only the wifi card is different.

On my computer with Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter i can't receive files.

- My Go version is: go1.11.6 linux/amd64

**Comment by claudiodangelis** [comment]
Hello @app4deepin, sorry to hear. Can you please paste here what is the URL generated by qrcp on the computer that fails the transfer?

**Comment by claudiodangelis** [comment]
Any news @app4deepin ?
