### ISSUE TITLE
comma in the file name prevents file transfer

### ISSUE THREAD

**Issue by michal037** [claudiodangelis/qrcp#162]
I'm opening this issue because: I have found a bug
qrcp 0.6.3

When I try to send a file with this command: `C:\Users\miich>qrcp C:\Users\miich\Desktop\a,b.pdf`.
The program shows the QR code and allows the phone to connect. But it immediately interrupts and the file is not downloaded. I noticed that the comma in the file name breaks functionality. The comma can be used in file names in Windows.

**Comment by claudiodangelis** [comment]
Thanks for reporting, this will be fixed in the next patch release 0.6.4, cheers, 
Claudio

**Comment by claudiodangelis** [comment]
I'm not a Windows user so I cannot replicate the issue, however,  from what I read here the comma is a special character of CMD and should be treatred accordingly:
 https://sourcedaddy.com/windows-7/escaping-special-characters.html
