### ISSUE TITLE
Cannot use on Windows when Hyper-V is enabled

### ISSUE THREAD

**Issue by mikuta0407** [claudiodangelis/qrcp#164]
When Hyper-V is enabled on Windows (for example, when using WSL2), NICs with IP address "192.168.0.*" are not displayed in the NIC list displayed by qrcp config.
It is displayed as 172.*.*.*, but it is not a valid URL and cannot be used.

**Comment by claudiodangelis** [comment]
@mikuta0407 thanks for reporting. 

Do you see the correct IP if you pass the `--list-all-interfaces` flag?

**Comment by mikuta0407** [comment]
I tried that option, but the NIC I wanted to use showed only IPv6 addresses.
(The address displayed by it can be used in Chrome on PC, but could not connect on iOS/Android. This may be a problem in my network settings.)
I use static IPv4 addresses, so I want to connect using IPv4 addresses if possible.

**Comment by claudiodangelis** [comment]
OK, I'm confident a solution could be easily found. Please allow me a few days, I'm a bit busy these days. 

Thanks!

**Comment by mikuta0407** [comment]
Sorry for the late reply.
It's such useful software that I don't mind waiting.
Thank you very much.

**Comment by claudiodangelis** [comment]
@mikuta0407  could you please take a screenshot or paste here the IPv6 showed by the tool? Thanks

**Comment by claudiodangelis** [comment]
@mikuta0407 also, did you try using the `-d [domain]` flag? Even if this is not the intended way to use it, you could try something like: `qrcp -d 192.168.0.X` , and the resulting URL will be `http://192.168.0.X:{port}/{...}`. It should work as long as your mobile is on the same network.

**Comment by mikuta0407** [comment]
I used "-d 192.168.0.90" and got the error "Error: invalid value for fully-qualified domain name".
![image](https://user-images.githubusercontent.com/13357430/86890016-a2634c00-c137-11ea-96eb-1efdd18cc426.png)

The list of IP addresses is as follows.
"イーサネット 6" is assigned the IP address actually used in the LAN.
![image](https://user-images.githubusercontent.com/13357430/86890163-db9bbc00-c137-11ea-9ac6-d4619a421493.png)
(The real NIC name is "Ethernet **_6_**", I think this is probably because I've reinstalled the driver several times before.)

**Comment by claudiodangelis** [comment]
Hello @mikuta0407, just wondering, what is the IP of the iOS/Android device you're trying to use qrcp with?

**Comment by mikuta0407** [comment]
@claudiodangelis  Devices other than PCs use DHCP to obtain IP addresses, so it is not fixed, but I think it is about "192.168.0.2~20".

**Comment by sky96111** [comment]
I enabled Hyper-V with qrcp working properly.Just "qrcp config" and reconfig qrcp interface with vEthernet.

**Comment by claudiodangelis** [comment]
Hello @mikuta0407, I fixed the issue where the IPv6 was showed in place of IPv4.
Can you please confirm you can use that now?
Thanks

**Comment by mikuta0407** [comment]
Thanks for the fix. I tried it with 0.8.4 and it worked!
Thank you!

**Comment by claudiodangelis** [comment]
@mikuta0407 I'm so glad to hear! It was a trivial bug, thanks for your months long patience!
Claudio
