### ISSUE TITLE
Why does the file name changes when it gets transferred?

### ISSUE THREAD

**Issue by issadarkthing** [claudiodangelis/qrcp#165]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [x] I have a question
- [ ] Other

- My Go version is:  go version go1.14 linux/amd64
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: /home/terra/go

It would be better if the file name of transferred file doesn't get appended by a random numbers.
![image](https://user-images.githubusercontent.com/50593529/87252574-d11a5300-c4a6-11ea-8594-70d6b533a45b.png)

**Comment by claudiodangelis** [comment]
Hello @issadarkthing, thanks for reaching out.
Honestly I'm not sure what's happening, qrcp does not append any random number to any transferred file.
If you are trying to receive a file into a folder which already has a file with the same name, then a `(1)` suffix (or _(2), (3), etc)) is added.

Are you experiencing this issue with `qrcp` or `qrcp receive`?

Thanks,
Claudio

**Comment by issadarkthing** [comment]
qrcp receive

**Comment by claudiodangelis** [comment]
Does it happen with all files? Can you exclude that the cause may be something other than qrcp?

**Comment by issadarkthing** [comment]
Just found out my phone app does that. I should've check that
