### ISSUE TITLE
Feature request:Add config to enable a fixed address

### ISSUE THREAD

**Issue by sky96111** [claudiodangelis/qrcp#166]
I'm opening this issue because:
Though random appendix can be disabled in config,but the difference between "send" and "receive" URL makes it difficult to write in a ntc tag(two tags are needed). 

After disabling in receive the URL is like http://192.168.123.143:233/receive/qrcp
But in send it likes http://192.168.123.143:233/send/qrcp

Dose it possible to add a config to make the URL same in receive and send?Like http://192.168.123.143:233/qrcp .This will be helpful for nfc trigger users.Thanks a lot.

- [ ]  I have found a bug
+ I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_

**Comment by claudiodangelis** [comment]
Hi @sky96111, thanks for requesting this feature! It requires some refactoring but it can be definitely done.

Cheers,
Claudio
