### ISSUE TITLE
Provide a library version

### ISSUE THREAD

**Issue by mubashir-rehman** [claudiodangelis/qrcp#177]
I'm opening this issue because:
I think there is a need to provide this amazing piece of art as a library to be used by other apps.

**Comment by claudiodangelis** [comment]
Hello @mubashir-rehman, thanks for opening this feature request.
Please allow me some time to think of a possible implementation & use cases for this, thank you!

**Comment by mubashir-rehman** [comment]
Thanks a lot for your response. Looking forward to it

**Comment by claudiodangelis** [comment]
Hello @mubashir-rehman, after some thinking, I don't see how this application could be integrated as a library into other applications. The best way to integrate is probably just to simply start the program as a sub process.

Thanks!
C
