### ISSUE TITLE
Feature request: In memory zip

### ISSUE THREAD

**Issue by imba-tjd** [claudiodangelis/qrcp#178]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

I have 12GB RAM, but my SSD's performance is poor. When I send large files located in my HDD, my two storages would be in 100% usage in terns. I think it would be good if we can make use of the RAM.

**Comment by claudiodangelis** [comment]
Hi, I never thought about this before. Will do some research, thanks!

**Comment by fenilgmehta** [comment]
[Sweech](https://play.google.com/store/apps/details?id=com.sweech&hl=en&gl=GB) on android does this when we download folder from another device.

**Comment by claudiodangelis** [comment]
Hello, I'm going to close this issue for now. The process of creating the zip file is delegated to a small library which apparently does not support in-memory zip files: github.com/jhoonb/archivex
