### ISSUE TITLE
How to set path for windows?

### ISSUE THREAD

**Issue by g8up** [claudiodangelis/qrcp#186]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [x] I have a question
- [ ] Other

- My Go version is: _go version go1.11.2 windows/amd64_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _D:\go-path_

I have set the config `path` as `d:/myfile`，but the file is still saved at `C:\Users\Administrator`。

- .qrpc.json
```json
{
    "interface": "以太网",
    "port": 9999,
    "keepAlive": true,
    "path": "d:/myfile",
    "secure": false,
    "tls-key": "",
    "tls-cert": ""
}
```

**Comment by claudiodangelis** [comment]
Hello @g8up, this is interesting. 
Did you try with `D:\myfile` (forward slash rather than backward's)?

**Comment by g8up** [comment]
# Case 1
- .qrcp.json
```json
{
    "interface": "以太网",
    "port": 9999,
    "keepAlive": true,
    "path": "D:\myfile",
    "secure": false,
    "tls-key": "",
    "tls-cert": ""
}
```
- echo 
```
C:\Users\Administrator>qrcp receive
Error: invalid character 'm' in string escape code
Run `qrcp help` for help.
```

# Case 2
- .qrcp.json
```json
{
    "interface": "以太网",
    "port": 9999,
    "keepAlive": true,
    "path": "D:\\myfile",
    "secure": false,
    "tls-key": "",
    "tls-cert": ""
}
```
- echo in cmd
```
C:\Users\Administrator>qrcp receive
Scan the following URL with a QR reader to start the file transfer:
http://192.168.3.46:9999/receive/D:\myfile
(qrcode img)
```
I got a `404 page not found ` after scanning on mobile phone.

**Comment by claudiodangelis** [comment]
Hello, I believe there is some confusion here.
The "path" in the configuration file is not the path where the files are downloaded.
At this time you can only specify it by using the `-o` or `--output` flag, for example:

```sh
qrcp receive --output "D:"
```

or 

```sh
cd D:
qrcp receive
```

If you don't specify the output directory, the current directory is chosen. 
There is an open pull request about introducing a "default output" directory, but that's still a work in progress: https://github.com/claudiodangelis/qrcp/pull/183
Hope this clears things up, thanks!
Claudio
