### ISSUE TITLE
XDG_CONFIG_HOME support?

### ISSUE THREAD

**Issue by jedahan** [claudiodangelis/qrcp#187]
I'm opening this issue because:

- [x] I want to request a feature
- My Go version is: 1.15.4
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: /home/micro/.cache/go

---

If XDG_CONFIG_HOME is defined, it would be nice to default the qrcp.json to `${XDG_CONFIG_HOME}/qrcp/config.json` or `${XDG_CONFIG_HOME}/qrcp.json`.

**Comment by claudiodangelis** [comment]
Hello @jedahan, sorry for the late reply, this seems to be interesting.
I will consider this for the next release, thanks!
C

**Comment by claudiodangelis** [comment]
Hello @jedahan, the XDG support is now available thanks to the work of @samhh.
Thanks both for suggesting and implementing the feature.

Claudio
