### ISSUE TITLE
on macOS 11.0.1, with 0.7.0 from homebrew, transferred data is empty

### ISSUE THREAD

**Issue by luckman212** [claudiodangelis/qrcp#188]
I'm opening this issue because:

- [x] I have found a bug
- My Go version is: `go version go1.15.6 darwin/amd64`
- My `GOPATH`is set to: `/Users/luke/golang`

I installed `qrcp` via Homebrew and ended up with 0.7.0
configured with `qrcp config` and tried a few times to transfer some small files (text, png) to my iPhone, but every time ended up with a blank white page. I then tried opening the URL from a desktop browser and got the same thing... empty white page, with nothing at all in view-source. I am doing this from the LAN directly, no NAT/firewall/port forwarding/DNS involved.

no errors etc printed to console, not sure how to debug further...

here is my `.qrcp.json`
```json
{
    "fqdn": "macmini.lan",
    "interface": "any",
    "port": 0,
    "keepAlive": true,
    "path": "",
    "secure": false,
    "tls-key": "",
    "tls-cert": ""
}
```

thank you

**Comment by anyunpu** [comment]
I found a problem with a space behind the link address obtained by the broom, which prevented the download from starting normally（我发现一个问题,扫码获取的链接地址后面有空格,导致无法正常下载）

**Comment by claudiodangelis** [comment]
Hello @luckman212 , @anyunpu  not sure what to say at this time, please allow me some time to research.
Thanks,
C

**Comment by claudiodangelis** [comment]
@luckman212 rather than using `interface: any`, can you try with your actual interface?

**Comment by luckman212** [comment]
@claudiodangelis thanks for trying.

changing interface from `any` to `en0` did not work.
I get `ERR_CONNECTION_REFUSED` when trying the URL
i checked with `netstat` and found that qrcp is binding to my ipv6 address only, not listening on ipv4 at all. That seems to be where the bug lies................

**Comment by claudiodangelis** [comment]
Hello @luckman212, thanks, I'm hearing about similar issues.
Let me research something, will try to get back to you soon.

**Comment by luckman212** [comment]
Hi @claudiodangelis 

I'm on v0.8.2 now (thank you) and setting interface to `any` works around the IPv6 problem. See also #196

But it's odd that the IPv4 isn't being detected on interfaces with dual-stack V4/V6 IPs. E.g. here I have output on my Mac that has 2 interfaces- en0 (Ethernet) that has both a v4 (192.168.20.40) and a v6. Only the v6 is shown. The WiFi interface (en1) does not have v6 enabled and shows the 192.168... address:

```
mini:~ $ qrcp config --list-all-interfaces
Use the arrow keys to navigate: ↓ ↑ → ← 
? Choose interface: 
  ▸ en1 (192.168.1.182)
    lo0 (127.0.0.1)
    en0 ([2603:7000:4842:700:8b6:6c93:9d69:8175])
    any (0.0.0.0)
```

**Comment by claudiodangelis** [comment]
@luckman212 hi, found the bug, which is actually a regression. Will release a new version soon. Thanks!

**Comment by claudiodangelis** [comment]
@luckman212 new version is out, should hopefully fix the issue for you and many more!
Please let me know if it works... thanks!

**Comment by claudiodangelis** [comment]
Oops, I actually introduced a new bug, which is now fixed in version 0.8.4.

**Comment by luckman212** [comment]
It will probably take a little while for the new version to be picked up by Homebrew, but I'll check as soon as it hits, thanks @claudiodangelis !

**Comment by claudiodangelis** [comment]
Hello everyone, is anyone still encountering this issue? If so, please re-open this ticket.
Thanks!
