### ISSUE TITLE
Support opening link in server-side ?

### ISSUE THREAD

**Issue by spin6lock** [claudiodangelis/qrcp#189]
I'm opening this issue because:

- [X] I want to request a feature

- My Go version is: go version go1.15.1 linux/amd64
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: 

Hi, thanks for the great work of qrcp ! I would like to read long article from PC instead of mobile phone. So I add an option for `qrcp receive`. Mobile phone scan code and paste link. Then qrcp open link by browser on server side, without creating temporary txt file on PC. Is this feature appropriate to qrcp ? Or qrcp stick to file transfer only ?

**Comment by claudiodangelis** [comment]
Hello @spin6lock, thanks for this proposal.
While this is technically feasible, it will be a bit out of this tool's purpose. I believe there are more efficient and mobile-native ways of achieving the same thing, for example by sharing the link via email, or using one of the hundreds bookmarking services.
However, in `qrcp` there is already a feature to allow transferring of text snippets, maybe you could consider using that: run `qrcp receive`, and on the mobile page check the "Show text options" box and paste the article's link in the "Text" field:

![image](https://user-images.githubusercontent.com/941963/102901168-93662100-446d-11eb-8c5e-6c4bfb1b9373.png)

Hope this helps, and thanks again for taking the time to propose a new feature.
Cheers,
Claudio

**Comment by claudiodangelis** [comment]
Something like this would work:

Run this in the command line:
```
qrcp receive ; firefox $(cat link.txt)
```

And enter "link" in the title field (the .txt extension is created automatically), and the URL in the text field.

Please let me know if that can be a good workaround for you.
Thanks!

Claudio

**Comment by spin6lock** [comment]
@claudiodangelis Thanks for your reply, this workaround works for me:+1:
