### ISSUE TITLE
Cannot Open the Link Generated

### ISSUE THREAD

**Issue by wwwCielwww** [claudiodangelis/qrcp#191]
Hi! Thank you very much for the great work!

My OS is Windows 10, and I am using an Android phone. 

Following the README, a QR code for sending the file is successfully generated in command line. However, I failed to open the link through my phone:  it says
`Your Internet access is blocked ...`

I tried to shut down my firewalls but it didn't work. Could anyone give me some clues on how to address this?

Many thanks!

**Comment by claudiodangelis** [comment]
Hi @wwwCielwww, sorry to hear.
Are you using a VPN in Windows?

**Comment by wwwCielwww** [comment]
Ahh nope. 
The IP address section of the link generated seems weird: http://[2408:832f:20a0:6d10:1032:7ee4:4911:8]:56804/send/qq9c
Maybe it has something to do with this?

**Comment by claudiodangelis** [comment]
Please try running the config wizard with the `--list-all-interfaces` flag, and look through the interfaces to find the one with the right IP.

```
qrcp config --list-all-interfaces
```

Please let me know if that helps, thanks.

**Comment by wwwCielwww** [comment]
> Please try running the config wizard with the `--list-all-interfaces` flag, and look through the interfaces to find the one with the right IP.
> 
> ```
> qrcp config --list-all-interfaces
> ```
> 
> Please let me know if that helps, thanks.

It works like a charm. Thanks a lot for your effort!!
