### ISSUE TITLE
Encountering "system cannot find the file" when running "qrcp receive"

### ISSUE THREAD

**Issue by noelforte** [claudiodangelis/qrcp#192]
I'm opening this issue because:

- [x] I have found a bug

- My Go version is: ` go1.16 windows/amd64`
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: (no output returned)

When I run `qrcp receive`, the following error message is thrown:

```
2021/03/04 17:41:04 error starting the server: open : The system cannot find the file specified.
```

Calling `qrcp v0.7.0` from Windows PowerShell running on:

```
Edition           Windows 10 Pro
Version           20H2
Installed on      ‎2/‎22/‎2021
OS build          19042.844
Experience        Windows Feature Experience Pack 120.2212.551.0
```

**Comment by sdetweil** [comment]
did u give it a path to the output?    --output path_to_folder

**Comment by noelforte** [comment]
Yep. Still a bust.

```
PS C:\Users\Me> qrcp receive --output .\Desktop\
Scan the following URL with a QR reader to start the file transfer:
https://■■■.■■■.■■■.■■■:4283/receive/bun8

(QR CODE)

2021/03/21 22:18:26 error starting the server: open : The system cannot find the file specified.
```

**Comment by sdetweil** [comment]
@noelforte   I think u would use the linux naming ./Desktop
(the / works in internal api calls.)

**Comment by noelforte** [comment]
Nope that doesn't change anything, still getting a `The system cannot find the file specified.`

**Comment by sdetweil** [comment]
what if u try just .

**Comment by noelforte** [comment]
same error. it appears to be trying to launch a directory that doesn't exist, the extra space after `open` in `error starting the server: open : The system cannot find the file specified.` would imply a path being there, a la `open <pathname>:` but there isn't one, so whatever is getting called isn't passing through appropriately.

**Comment by sdetweil** [comment]
it does look for ~/.qrcp.json as the default config file  
so maybe in the current folder with contents of  { "port":"0" }
and parms -c ./qrcp.json

**Comment by claudiodangelis** [comment]
Hello @noelforte, I believe this has nothing to do with the destination directory, but rather to the files of your private key and certificate used for starting the server.

Did you set the path of those two files correctly in the config? Does it work with `--secure=false`?

Thanks,
Claudio

**Comment by noelforte** [comment]
@claudiodangelis weird, it seems to be working now, just tried again to download it and transfer a file, worked without a hitch. maybe there was something misconfigured or perhaps it was using https and I didn't realize it. Either way I'm good to go now. Thanks!

**Comment by claudiodangelis** [comment]
Ah, really good to hear!
