### ISSUE TITLE
interface address is weird..

### ISSUE THREAD

**Issue by LavikLee** [claudiodangelis/qrcp#196]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [X] I have a question
- [ ] Other

My OS is windows 10, I have a weird thing when I use qrcp. I choose interfaces and the address of WLAN looks weird, like " WLAN ([2402:7500:58e:bcec:c8a9:673:4fab:8107])" . I can receive or send any file by this address. How do I figure out it?

**Comment by claudiodangelis** [comment]
That's an IPv6, not sure why it's not picking up the IPv4.
Can you run the config wizard with the `--list-all-interfaces` flag, scroll through the list and see if you find your IPv4?

```
qrcp config --list-all-interfaces
```

![image](https://user-images.githubusercontent.com/941963/114730417-24287b80-9d41-11eb-873f-ca204acbacc5.png)

Thanks,
Claudio

**Comment by Supresun** [comment]
> That's an IPv6, not sure why it's not picking up the IPv4.
> Can you run the config wizard with the `--list-all-interfaces` flag, scroll through the list and see if you find your IPv4?
> 
> ```
> qrcp config --list-all-interfaces
> ```
> 
> ![image](https://user-images.githubusercontent.com/941963/114730417-24287b80-9d41-11eb-873f-ca204acbacc5.png)
> 
> Thanks,
> Claudio

I have the same problem with Laviklee. My computer has both ipv4 and ipv6 address, but the qrcp just only show ipv6 address, although I added the` --list-all-interfaces` command option. It seems doesn't help.

**Comment by claudiodangelis** [comment]
@Supresun thanks for the feedback, will try to figure out how to reproduce (I'm not a Windows user).

**Comment by claudiodangelis** [comment]
Hello @Supresun @LavikLee, I just released a new version https://github.com/claudiodangelis/qrcp/releases/tag/0.8.3 which should fix the issue for you.
Can you please give it a try and let me know?

Cheers,
Claudio

**Comment by LavikLee** [comment]
Thanks a lot. I enabled the IPv6 protocol and tried the new qrcp. It looks
everything is fine, gets the IPv4 address correctly.

claudiodangelis ***@***.***> 于 2021年4月25日周日 上午12:53写道：
