### ISSUE TITLE
Improve quit action for better integration

### ISSUE THREAD

**Issue by sayanarijit** [claudiodangelis/qrcp#198]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_

Hi this is a great tool. I am trying to integrate `qrcp` with [xplr](https://github.com/sayanarijit/xplr). However, `ctrl+c` to kill the server also kills `xplr` (not sure why). Is it possible to fix it or map quit to some other key?

**Comment by claudiodangelis** [comment]
Hello @sayanarijit, thanks for the suggestion, will try to think about something.

 `xplr` looks really cool btw!

**Comment by sayanarijit** [comment]
Thanks, let me know if I can help in any way.

**Comment by sayanarijit** [comment]
FYI I'm currently using [this workaround](https://github.com/sayanarijit/xplr/wiki/Hacks#share-files-via-qr-code-on-lan).

**Comment by claudiodangelis** [comment]
Are you binding the stdin of the process (qrcp in this case) to the stdin of the os? My feeling is that CTRL+C is captured by the shell running xplr, not qrcp's!

**Comment by claudiodangelis** [comment]
I know nothing about Rust, but this seems that you should add `.stdin(Stdio::piped())` somewhere around https://github.com/sayanarijit/xplr/blob/main/src/app.rs#L1257 ?

**Comment by sayanarijit** [comment]
I'm using `Stdio::inherit()` in https://github.com/sayanarijit/xplr/blob/0c82a645d98c6fde0aa8047079dfddbfb0eb02df/src/main.rs#L48 to be able to interact with the subprocess.

**Comment by sayanarijit** [comment]
But I see the point. Other programs like `ncdu` captures the `stdin` so `xplr` doesn't exit.

**Comment by sayanarijit** [comment]
Maybe I can use some kind of runner that will capture the `stdin` and manage `qrcp`. Though, I'm not sure if there's anything like that.

**Comment by claudiodangelis** [comment]
@sayanarijit got it, mm, probably `qrcp` should capture the stdin then...
I will research later!

**Comment by claudiodangelis** [comment]
@sayanarijit it seems like closing `ncdu` with CTRL+C makes `xplr`  exit as well...

**Comment by sayanarijit** [comment]
Ah, you're right... I confused `ncdu` with [diskonaut](https://github.com/imsnif/diskonaut). Different programs different implementations of `ctrl+c` :D.

**Comment by sayanarijit** [comment]
FYI [this is how sfz](https://github.com/weihanglo/sfz/pull/63) solved the issue.

**Comment by claudiodangelis** [comment]
Hello @sayanarijit, I honestly don't like that solution.
I already implemented the server shutdown on "q" pressing, will push a new release in the next hours/days.

Cheers,
Claudio

**Comment by sayanarijit** [comment]
Awesome. Thanks for the effort.

**Comment by claudiodangelis** [comment]
Well, apparently it only took a few minutes! Version 0.7.1 is out and has the "exit with 'q'" ability.
Please let me know if everything looks ok now, cheers!

**Comment by sayanarijit** [comment]
![qrcp-quit](https://user-images.githubusercontent.com/11632726/115209673-74c21f00-a11b-11eb-8652-b160f25e7d5c.gif)

Unfortunately it's not working on Manjaro.

bin: https://github.com/claudiodangelis/qrcp/releases/download/0.7.1/qrcp_0.7.1_linux_x86_64.tar.gz
os:

██████████████████  ████████   sayanarijit@katana
██████████████████  ████████   ------------------
██████████████████  ████████   OS: Manjaro Linux x86_64
██████████████████  ████████   Host: 81YM IdeaPad 5 14ARE05
████████            ████████   Kernel: 5.9.16-1-MANJARO
████████  ████████  ████████   Uptime: 3 hours, 33 mins
████████  ████████  ████████   Packages: 1469 (pacman), 1 (dpkg), 767 (nix-user), 9 (
████████  ████████  ████████   Shell: zsh 5.8
████████  ████████  ████████   Resolution: 1920x1080
████████  ████████  ████████   DE: Plasma 5.21.3
████████  ████████  ████████   WM: KWin
████████  ████████  ████████   WM Theme: borderline
████████  ████████  ████████   Theme: ChromeOSDark [Plasma], Breeze [GTK2/3]
████████  ████████  ████████   Icons: Tela-dark [Plasma], Tela-dark [GTK2/3]
                               Terminal: alacritty
                               CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.00
                               GPU: AMD ATI 04:00.0 Renoir
                               Memory: 2481MiB / 7388MiB

**Comment by sayanarijit** [comment]
Also, I think it'd be better to prompt users to use `q` for **graceful shutdown** so that they don't go for `ctrl+c` in the first attempt.

**Comment by claudiodangelis** [comment]
Mm, I must have missed something because when I tested it worked. Not sure what happened!
About CTRL+C, it's already tied to a graceful shutdown process, thanks for pointing it out.

**Comment by claudiodangelis** [comment]
Should be ok now

**Comment by sayanarijit** [comment]
Awesome :+1: . It works. But `ctrl+c` stopped working from `xplr`. So, I think the way you are capturing `q`, you can also capture `ctrl+c` and then `q` and `ctrl+c` should behave th esame way.

**Comment by sayanarijit** [comment]
Actuallt `ctrl+c` stopped working altogether.

**Comment by sayanarijit** [comment]
BTW before the next release, you can of-course ping me if you need an extra hand for testing.

**Comment by claudiodangelis** [comment]
Ultimately fixed! Thanks again for the suggestion!

**Comment by sayanarijit** [comment]
Confirmed. Everything works fine now. Updated the command in [wiki](https://github.com/sayanarijit/xplr/wiki/Hacks#sendreceive-files-via-qr-code-on-lan).
