### ISSUE TITLE
Feature Request - Add option to save files in a default folder

### ISSUE THREAD

**Issue by ATrogolo** [claudiodangelis/qrcp#200]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

Hi Claudio,
I'm opening this PR to follow up our mail conversation when I suggest you to add an option to set a path where 'received' files will be saved. 
The current scenario is: the file will be downloaded in the same folder you're launching `qrcp`. 
It would be nice if the user can specify a default folder (in the config file) to store the downloaded files. 

Thanks for you job 🙏
Andrea

**Comment by claudiodangelis** [comment]
Hello, this feature has just been implemented and is available as per version 0.8.0.
Thanks again for suggesting this feature, ciao!

Claudio
