### ISSUE TITLE
qrcp 0.8.1 test build failed

### ISSUE THREAD

**Issue by chenrui333** [claudiodangelis/qrcp#201]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_

---

👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test failure</summary>

```
==> curl -H "User-Agent: Mozilla" http://localhost:58451/send/testing
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 58451: Connection refused

Error: qrcp: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: 7
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/2386151398
relates to https://github.com/Homebrew/homebrew-core/pull/75523

**Comment by claudiodangelis** [comment]
Hello @chenrui333, I recently added a keyboard listener to capture the "q" key press and initiate a graceful shutdown. 
In order for that function to work, it needs to connect to the current terminal, which apparently cannot be done in the Github CI/CD, see the failure reason of the `qrcp` command: https://github.com/Homebrew/homebrew-core/runs/2386151398#step:7:75

I will release a hotfix later today or tomorrow, thank you very much for taking the time to report this problem.

**Comment by claudiodangelis** [comment]
@chenrui333 I release version 0.8.2 which should not break the build.
Cheers

**Comment by chenrui333** [comment]
let me give 0.8.2 a try, thanks @claudiodangelis !

**Comment by chenrui333** [comment]
It works, thanks @claudiodangelis!

**Comment by chenrui333** [comment]
Closing the issue.
