### ISSUE TITLE
Installation Bug on MacOS Big Sur - Binary cannot be verified.

### ISSUE THREAD

**Issue by TheSYNcoder** [claudiodangelis/qrcp#203]
I'm opening this issue because:

- [X] I have found a bug

- My Go version is: _(go version go1.16.4 darwin/amd64)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(/Users/shuvayan/mygo)_

During the installation of qrcp on MacOs Big Sur, 

I downloaded the binary and extracted and put the binary in path, after doing `chmod +x`.
However on running
```
qrcp --help
```

MacOs comes with a prompt 
```
"qrpc" cannot be opened as the developer cannot be verified.
```

**Comment by SuperSandro2000** [comment]
Thats not a bug but Apple trying to sell expensive stuff.

Please follow https://github.com/hashicorp/terraform/issues/23033#issuecomment-540417305

**Comment by TheSYNcoder** [comment]
Hey thanks it worked.
