### ISSUE TITLE
Error on pi zero 

### ISSUE THREAD

**Issue by effeottantuno** [claudiodangelis/qrcp#204]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [X] Other

- My Go version is: _(go version go1.14.4 linux/arm)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(/home/pi/go)_
- Im using a raspberry pi zero via ssh and  when i try to use qrcp i get the error: "Instruction not allowed "

**Comment by effeottantuno** [comment]
i followed the guide, i tried with all the arm packages

**Comment by claudiodangelis** [comment]
Hello, sorry for the long wait. I have no idea to be honest, maybe you can try reaching out to the [GoReleaser team](https://github.com/goreleaser) , which makes the tool I use to release qrcp.

Thanks.
