### ISSUE TITLE
Windows 10 Pro - Site is not reachable

### ISSUE THREAD

**Issue by amitpatelx** [claudiodangelis/qrcp#206]
I am trying to use qrcp(qrcp_0.8.4_Windows_x86_64.tar.gz) on Windows 10 Pro 20H2 64 bit

I am trying to receive a file from mobile/other PC on the same wifi network. The command line shows the QR code just fine but when I scan on mobile/open link in other PC, the browsers keep on waiting and finally times out with an unreachable error.

I have used default options without changing anything. I tried to change all the available interfaces as well but didn't work either.

Do I have to enable anything in windows/system anywhere?

**Comment by claudiodangelis** [comment]
Hello @amitpatelx, I'm not a Windows user, but I believe you should not enable anything.
Can you please paste here an URL of the qrcp output? 

If you don't want to paste it publicly you can send me an email claudiodangelis@gmail.com .

Thanks,
C

**Comment by iainsgillis** [comment]
Hi, @amitpatelx  --

I had to explicitly allow qrcp (installed via scoop) to communicate through Windows Defender Firewall.

I'm currently running 64-bit Win11Pro v21H2.

Screenshot of my current (working) configuration:

![image](https://user-images.githubusercontent.com/10743672/135894695-92ef4251-2dc0-4d26-abc5-6d3b68a71f3a.png)

**Comment by claudiodangelis** [comment]
Hello @amitpatelx, are you still getting this issue with the latest version? If so, please feel free to re-open this issue.
Thanks!
C
