### ISSUE TITLE
404 is returned if keep-alive is enabled for sending

### ISSUE THREAD

**Issue by lonble** [claudiodangelis/qrcp#210]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

- ~~My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_~~
- ~~My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_~~

I installed `qrcp-bin` from AUR, so GO is not installed. My qrcp version is 0.8.4.

When `keep-alive` is enabled to `send` files, the correct result will be returned when the URL is accessed for the **first** time, and `404` will be returned for the **second** and subsequent times. The 404 page is blank, which is different from the 404 page when the path is incorrect. 
This problem occurs only when sending, and everything is normal when keep-alive is enabled when receiving.
This has nothing to do with the device or browser. I reproduced the same problem on multiple browsers on my mobile device and local host.

**Comment by claudiodangelis** [comment]
Hello @lonble, thanks for reporting! This is definitely a bug.
I will have a look some time next week.

Thanks,
Claudio

**Comment by lonble** [comment]
There has been no new release for a long time. Has it been fixed in the latest code?

**Comment by claudiodangelis** [comment]
Hello,
this hasn't been fixed yet. Apologies,
Claudio

**Comment by claudiodangelis** [comment]
Hello @lonble , I'm trying to reproduce the issue to no avail. There is actually a bug which causes an error but that happens _after_ serving the file, which is being correctly served anyway.

I tried with a browser and curl and the scenario you describe doesn't seem to happen.

Please feel free to reopen the issue if you're still having the issue with the latest release (0.8.6), thanks!

**Comment by lonble** [comment]
I downloaded version 0.8.6 from release. 404 still appears when I use the browser to access, but when I use curl to access, the content can be displayed, but I found something else in the output of `qrcp`
```
2022/03/13 01:01:33 http: panic serving 192.168.43.244:59554: sync: negative WaitGroup counter
goroutine 39 [running]:
net/http.(*conn).serve.func1(0xc0003fa1e0)
	/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:1800 +0x139
panic(0x86ff80, 0xa07af0)
	/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:975 +0x3e3
sync.(*WaitGroup).Add(0xc00026ccc0, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.14.15/x64/src/sync/waitgroup.go:74 +0x139
sync.(*WaitGroup).Done(0xc00026ccc0)
	/opt/hostedtoolcache/go/1.14.15/x64/src/sync/waitgroup.go:99 +0x34
github.com/claudiodangelis/qrcp/server.New.func2(0xa18d40, 0xc0003d0620, 0xc0003c0600)
	/home/runner/work/qrcp/qrcp/server/server.go:217 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc0002677a0, 0xa18d40, 0xc0003d0620, 0xc0003c0600)
	/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xd5c3a0, 0xa18d40, 0xc0003d0620, 0xc0003c0600)
	/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0001501c0, 0xa18d40, 0xc0003d0620, 0xc0003c0600)
	/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0003fa1e0, 0xa19d00, 0xc0003adb40)
	/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:2962 +0x35c
```

**Comment by claudiodangelis** [comment]
Yes, I'm deploying a fix for this as per #185. I'm also replacing the 404 with a proper error message and http status. Should be available in a few hours as per version 0.9.0.
Thanks!
C

**Comment by claudiodangelis** [comment]
Also, very important question: do you disabled cookies in your browser? That could explain the 404.

**Comment by lonble** [comment]
I did get an error message about cookies, but I didn't disable cookies.
I don't understand why cookies are needed, `--keep-alive` is useful for sharing files to multiple users, but it's not possible yet.
Btw, everything works fine when using curl.

**Comment by claudiodangelis** [comment]
Hello @lonble, cookies are needed because some browser may issue multiple requests for downloading big files, and we leverage on cookies to actually wait for all requests to be fulfilled before shutting down the server.

However, when `--keep-alive` is enabled we don't really need this workaround, so I just issued a new release, `0.9.1`, which skips the cookie part if that flag is on.

Please let me know if it works now, and thanks for your patience!
C

**Comment by lonble** [comment]
Hi @claudiodangelis, Thanks for the quick work, in version 0.9.1 everything works fine when `--keep-alive` is enabled.
When `--keep-alive` is not enabled, everything works fine with browser, however, when accessed with curl the server does not shut down as expected.
