### ISSUE TITLE
Could not upload more than 9 files from iOS 12.4.1

### ISSUE THREAD

**Issue by chitvan1988** [claudiodangelis/qrcp#220]
I'm opening this issue because:

- [ ] I have found a bug

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_
Used qrcp.exe latest 0.8.4 on windows  Could not upload more than 9 files from iOS 12.4.1.
And also browser crashes if trying to upload around 4000 files for backup purposes.

**Comment by claudiodangelis** [comment]
Hello @chitvan1988 thanks for reaching out.
Which error do you get trying uploading more than 9 files? Do you receive an error from qrcp or from the browser?

Thanks,
C

**Comment by claudiodangelis** [comment]
I will close this for inactivity. Please feel free to reopen, thanks!
