### ISSUE TITLE
Do not override "interface" in the configuration file

### ISSUE THREAD

**Issue by lonble** [claudiodangelis/qrcp#236]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [x] I have a question
- [ ] Other

I found a strange thing. When running `qrcp` for the first time, a `config.json` file is created, which holds the default software configuration. Everything looks normal except `interface`. `interface` does not hold the default like other options, but the interface I used the last time I ran `qrcp`. Every time I switch between ethernet and wifi I get `Error: unable to find interface`.
I tried setting `interface` to an empty string and the strange thing happened again. Whatever options are used on the command line will not overwrite the contents of the `config.json` file, except `interface`. I can only manually modify `config.json` every time I switch network environments.
I don't understand why `qrcp` store the value of `interface` by default, why overwrite the config file with the interface used the last time I ran `qrcp`. I think it should rescan available interfaces every time `qrcp` is run.

**Comment by claudiodangelis** [comment]
Hey, sorry for the huge delay! Yep, this seems to be a bug. However, I want to change the configuration file format from JSON to YAML in the next release, I will work on this too.

Thanks for reporting!

**Comment by claudiodangelis** [comment]
I think this should be fixed as of now.
