### ISSUE TITLE
feature request: add support for HTTPS

### ISSUE THREAD

**Issue by evilsocket** [claudiodangelis/qrcp#24]
Downloading files over HTTP is never a good idea, even if you're just downloading from your own laptop. Fortunately Go makes super easy having a HTTPS server, feel free to steal the code [here](https://github.com/bettercap/bettercap/blob/master/modules/http_server.go) and [here](https://github.com/bettercap/bettercap/blob/master/tls/cert.go#L14) ^_^

**Comment by avin** [comment]
what cert do you gonna use for local net IP address??

**Comment by evilsocket** [comment]
The code that I linked can either use pre generated PEM files or just automagically generate new ones and use them. On the phone side you should just need to either add them to the system store (and have them added as permanent security exceptions), or just allow the certificate temporarily in the browser session.

**Comment by avin** [comment]
too overwhelmed

**Comment by evilsocket** [comment]
lulz it's just that Go's crypto library makes this very easy, so why not? :D

**Comment by FrontMage** [comment]
What if I'm downloading from a remote server? I think this is a good feature to add.

**Comment by claudiodangelis** [comment]
> @FrontMage What if I'm downloading from a remote server? I think this is a good feature to add.


As of now, the tool won't work on remote server, as both ends are required to be on the same network.

However, I'm thinking about adding an `-external` (or `-remote`) flag which binds the server to the publicly accessible IP address of the host, to enable downloading from a remote server and in that case HTTPS support will be mandatory.

**Comment by FrontMage** [comment]
@claudiodangelis checkout my fork [here](https://github.com/FrontMage/qr-filetransfer) supporting by `-remote`.

**Comment by claudiodangelis** [comment]
Please have a look at this thread, this is an interesting idea which can be used to support HTTPS connections: https://github.com/claudiodangelis/qr-filetransfer/issues/42

**Comment by evilsocket** [comment]
@claudiodangelis I'm not sure I understand the reasoning behind this:

    However, I'm thinking about adding an -external (or -remote) flag which binds the server to the publicly accessible IP address of the host, to enable downloading from a remote server and in that case HTTPS support will be mandatory.

In my opinion HTTPS should be **always** mandatory (or at least the *default* behaviour that can be disabled optionally), regardless if the connection is happening from a remote server or your own laptop on a private network. Actually, the likelyhood of a MITM attack is exactly the same while you're using the tool on a private network (an attacker is mitm-ing in an office, or a public wifi, or hotel, or mc donalds...) and when you use it from/to a remote server (in which case, the attacker should mitm your connection on your network anyway ... or on the server network, which is unlikely).

Having said that, what complexities do you think enabling TLS by default would add? If there's anything you're concerned about maybe we can work out a better design?

**Comment by claudiodangelis** [comment]
@evilsocket  there is no complexity other than those you summarized earlier on this thread, and to be honest, _technical_ complexity is not a even concern. The problem, which by the way I'm perfectly fine with, might be the big trade-off between security and user experience: if you want to quickly send yourself a 150k PDF file over your own house network, you should not be bothered to add a security exception. And it's really great to hear you want to help on this, because I'm sure we will find a way to clear this tradeoff.

For example, can we make it a one-time, set-it-and-forget-it configuration? The tool creates and signs the certificate, users add it as a security exception.

If that is possible, if the tool is not yet configured it could serve an http page where it explains in clear words why the user will be redirected to an untrusted/not secure page, and how to add the security exception.

Do you think we can make this?

**Comment by evilsocket** [comment]
Then you only need to use the code I linked to generate the certificates and [this part](https://github.com/bettercap/bettercap/blob/master/tls/sign.go#L52) to sign them with a qr-filetransfer owned CA (that you can generate with the same exact code). The user can just add that CA to the system store and it's done ^_^ 

Or, since the cert is [already generated as CA itself](https://github.com/bettercap/bettercap/blob/master/tls/cert.go#L55), the user might just add the generated files instead of the global CA.

**Comment by NatoBoram** [comment]
Using the public-facing IPv6 of the machine would be a good idea to allow `-remote`. And if IPv6 is used by default, the `-remote` might not even be necessary! As for the certificate, a "one-time, set-it-and-forget-it configuration" is the best option one could wish for. 

If you want to add more mobile devices later on, maybe a command to send the required CA to import can be added as a command. For example, if someone runs `qr-filetransfer -cert`, the generated QR Code will be used to download the necessary CA to be imported by the client.

**Comment by FrontMage** [comment]
@NatoBoram How about some frontend technique, `qr-filetransfer -cert` generates a qrcode for the CA, after the CA download, there is a button click to download with https.

**Comment by claudiodangelis** [comment]
Just came across this project by @FiloSottile: https://github.com/FiloSottile/mkcert , might be worth having a look.

**Comment by claudiodangelis** [comment]
I'm keeping an eye on this: https://github.com/FiloSottile/mkcert/issues/45

**Comment by claudiodangelis** [comment]
Hi everyone, FYI I opened a PR for adding HTTPS support: #176 
I will be starting pushing commits over the weekend. 
Thanks!

**Comment by claudiodangelis** [comment]
The PR is ready for reviewers, just in case someone wants to give it a try.
Thanks!
C

**Comment by claudiodangelis** [comment]
HTTPS support has been introduced in version [0.7.0](https://github.com/claudiodangelis/qrcp/releases/0.7.0), thanks everyone for suggesting the feature.
