### ISSUE TITLE
is there a way to configure the message displayed on the mobile device after file transfer

### ISSUE THREAD

**Issue by sdetweil** [claudiodangelis/qrcp#244]
I'm opening this issue because:

- [ ] I have found a bug
- [x ] I want to request a feature
- [x ] I have a question
- [ ] Other

after the selected file uploads  the user gets a message that the file was uploaded to 

/temp/sssss/xxxx/foo/bar/

which they don't  know anything about.. (and don't need to know)

can I configure that message?

**Comment by sdetweil** [comment]
answer is not currently. 

'Done' page template just shows what server provides.

**Comment by sdetweil** [comment]
so, I got this working, at the moment, chop off the path, .. but this is really useless from pic from my phone as the names are nothing..  well, sorta.. date/timestamp

Successfully transferred to:
20220429_160014.jpg

at least for me I would  really prefer 

Successfully transferred 1 files

thats just a different template and the count of files, vs their names.

**Comment by claudiodangelis** [comment]
Thanks for your feedback @sdetweil, I'm a bit busy at the moment. Will get back to you as soon as I get some free time.
Cheers,
C

**Comment by sdetweil** [comment]
no problem

heres the summary  (count)  view

![Screenshot_20220520-102704_Chrome](https://user-images.githubusercontent.com/1498142/169561748-29a097f5-610c-4307-b473-b72db8162a0b.jpg)

**Comment by claudiodangelis** [comment]
Hello,
sorry for the long delay. At this time it's not possible to configure a message, as the HTML is hardcoded in the tool.
I would love to separate the HTML from the server code, and ideally have a separate repository for the web client, but I'm afraid this is going to take a very long time.

If you want, you can change the code yourself and rebuild the tool, the location of the HTML is in https://github.com/claudiodangelis/qrcp/blob/main/pages/pages.go

Thanks,
C
