### ISSUE TITLE
Not working properly in some browsers

### ISSUE THREAD

**Issue by Curtion** [claudiodangelis/qrcp#246]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_

Some browsers will pop up a download box. At this point the waitgroup count will immediately become 0

The result is the same as #147  . Scan the QR code and the server will close.

Browsers  E.g:

Edge on IOS
Quark on Android

**Comment by claudiodangelis** [comment]
Thanks for reporting. I will try to reproduce the issue on those two browsers. In the meantime, as a workaround, you can use the `--keep-alive` flag, which will leave the tool running.

Please let me know if that helps, thanks!

**Comment by Kuchteq** [comment]
Similarly, Brave on iOS behaves exactly the same

**Comment by rexendevar** [comment]
Does "leaving the tool running" mean indefinitely or just until the command is broken via ctrl C?

**Comment by claudiodangelis** [comment]
Hello, it will leave it running until CTRL C is pressed!
