### ISSUE TITLE
Using qrcp from python

### ISSUE THREAD

**Issue by Liampour** [claudiodangelis/qrcp#248]
Hello 
Congratulations for your amazing work!!
I am trying to build a python script that captures an image and sends it via qr.
How can I use qrcp to create qr code from python script?
Cheers!!

**Comment by claudiodangelis** [comment]
Hello @Liampour , apologies for the super late reply!
If your goal is to use `qrcp` just for creating the QR code and still having all the transfer logic in Python, then `qrcp` is not the right tool for that.
Please have a look at the `qrcode` Python package, you can find a good tutorial here: https://towardsdatascience.com/generate-qrcode-with-python-in-5-lines-42eda283f325

Hope this helps, and thank you for reaching out!

Claudio
