### ISSUE TITLE
[minor] DeadLink in Docs

### ISSUE THREAD

**Issue by TrevCan** [claudiodangelis/qrcp#250]
I'm opening this issue because:

- [x] I have found a bug

The webpage <https://claudiodangelis.com/qrcp/> has a `LICENSE` link at the end: <https://claudiodangelis.com/qrcp/LICENSE>. It returns a 404 error in Github Pages.

**Comment by claudiodangelis** [comment]
Good catch! Will fix it soon :-)

**Comment by claudiodangelis** [comment]
Fixed, thanks! :joy:
