### ISSUE TITLE
releases doesnt show x86 version, unless u push the dropdown

### ISSUE THREAD

**Issue by sdetweil** [claudiodangelis/qrcp#251]
I have a magicMirror module that uses your app. 
https://github.com/sdetweil/uploadPics
and for smart-mirror
https://github.com/sdetweil/sm-uploadPics

i pull the releases page , and get the  version that matches the platform.. 

except x86-64 is hidden unless u push the dropdown , which I can't do from the script.. 
is there an alternative list? 

```
#!/bin/bash

arch=$(uname -m)
if [ $arch == 'armv7l' ]; then
   arch=armv7
fi

fn=$(curl -sL https://github.com/claudiodangelis/qrcp/releases | grep -m1 $arch | awk -F'"'  '{print $2}')
if [ '$fn'. != '.' ]; then
   # download the  file for this machine
   curl -sL https://github.com$fn > xx.deb
fi
```

**Comment by claudiodangelis** [comment]
Hi,
you could scrape somewhere the latest release number (currently `0.9.1`) and then scrape this URL which shows the full list:

```
curl https://github.com/claudiodangelis/qrcp/releases/expanded_assets/0.9.1
```
