### ISSUE TITLE
Error with many arguments in util/util.go

### ISSUE THREAD

**Issue by gpxlnx** [claudiodangelis/qrcp#252]
When I try to compile the package I get the following message

"
src/github.com/claudiodangelis/qrcp/util/util.go:65:38: too many arguments in call to zip.Add
have(string, *os.File, fs.FileInfo)
want(string, []byte)
"
I would like to know why several arguments are passed and if this could not be changed on line 65 of the util/util.go file?

Thank you and congratulations for the work

- [ ] I have a question
- My Go version is: 1.19

**Comment by claudiodangelis** [comment]
Hi, I have seen this before, I think it's related to a mismatching version of the github.com/jhoonb/archivex library, which the util package relies upon.

**Comment by claudiodangelis** [comment]
Hello, sorry for the huge delay, I tried to reproduce the issue on a fresh machine but everything is building correctly now.
I will close this issue for now but please feel free to reopen it if you're still affected and we will figure it out.
Thanks for taking the time to report the problem!
Claudio
