### ISSUE TITLE
[enhancement] Right-click context menu shortcuts for qrcp (Windows)

### ISSUE THREAD

**Issue by egemenertugrul** [claudiodangelis/qrcp#259]
I realized that this tool would be much more useful with the added feature of using right-click context menu on selected items/directories to send/receive files.

So I created some helper scripts to add & remove the necessary shortcuts and registry keys & values on Windows machines:

Attached: [qrcp_context_menu_helper.zip](https://github.com/claudiodangelis/qrcp/files/10013730/qrcp_context_menu_helper.zip)

I hope it helps!

<hr>

# Installation:
Run `ADD.bat` to install, `REMOVE.bat` to uninstall the key/values and shortcuts. That's it.

# Usage:

### Single:
To send a single file, right-click on the selected file, and select `qrcp send`.
![send_single](https://user-images.githubusercontent.com/10247966/201950878-7fc79446-f817-4725-bed2-f4f7eabc35ca.jpg)

### Multiple:
To send single or multiple files (zipped), right-click on the selected file(s), `Share`, and select `qrcp Send Multiple`.
![send_multiple](https://user-images.githubusercontent.com/10247966/201950905-45b69af7-f3f8-47b4-870f-2e1ab6c9076c.jpg)

## Receive:
To receive files to the selected directory, right-click in an empty spot of the folder, and select `qrcp receive`.
![receive_multiple](https://user-images.githubusercontent.com/10247966/201950991-81a59fbe-d843-47f9-9080-b32104d2bd89.jpg)

**Note:** If config.json has the `output` field set, it will receive files to that specified path regardless. So make sure to clear it to use this functionality.

<hr>

The primary problem for me here is that I am unsure how to PR this feature to this repository, as it is 100% Go and non-Windows specific. 

In addition, if the .exe file could get an icon, it would be straightforward to add icons to these shortcuts as well.

**Comment by claudiodangelis** [comment]
This is fantastic, thanks!
Will review soon and let you know.
Thanks,
C

**Comment by claudiodangelis** [comment]
Hello @egemenertugrul , apologies for the late follow up! It's been almost one year :see_no_evil: 
What about creating a repository on your own with these scripts and a detailed README with all the information you wrote above.
This way people from the community will be able to improve it, suggest new ideas and so one.
Once done, I will be happy to put a link to the repository in the README of qrcp.

Thanks again for taking the time to work on this,
Claudio
