### ISSUE TITLE
Wake lock within file-upload webpage - Android

### ISSUE THREAD

**Issue by gkathir15** [claudiodangelis/qrcp#260]
I'm opening this issue because:
- [enhancement ] Mobile - Android
- request [wake lock](https://developer.mozilla.org/en-US/docs/Web/API/WakeLock) within the file upload webpage, this will make the screen while the webpage is on.
- this could in avoiding any interruptions in upload if any.

**Comment by leestarb** [comment]
Oh! This is a really frustrating moment when you see that the transfer aborted due to phone screen turn off

**Comment by claudiodangelis** [comment]
Thanks for reporting, will have a look during the week!

Claudio

**Comment by claudiodangelis** [comment]
I will close this for now, as I'm planning to rework the UI in the coming months.
Thanks!
