### ISSUE TITLE
QRCP does not delete the temporary zip file after it is sent under Windows

### ISSUE THREAD

**Issue by TilsitMonk** [claudiodangelis/qrcp#277]
I'm opening this issue because:
- [x ] I have found a bug

Steps to reploduce:

1. Execute QRCP:
qrcp send _ANY_FOLDER_NAME_

2. Receive ZIP file at mobile device or exit by pressing Q

The problem is observed on
- Windows 7 SP1 x64
- Windows 10 (10.0.17763.1999) x64

![2023-05-03_082010](https://user-images.githubusercontent.com/132430608/235845037-aff049f7-387d-4a74-bfba-05540f22c27a.jpg)

**Comment by claudiodangelis** [comment]
Hello! Apologies for the late reply!
It looks like something to be looked into...
Please allow me some time to look into it, thanks!

**Comment by ilaoyao** [comment]
> Hello! Apologies for the late reply! It looks like something to be looked into... Please allow me some time to look into it, thanks!

unfortunately, it still exist!

**Comment by claudiodangelis** [comment]
Hello! There is an open PR which should fix it.
I'm still reviewing it, it should be available in version 0.11.0, which will be released during the weekend.

This is the PR: #304

**Comment by claudiodangelis** [comment]
Hello, this should have been fixed now in version 0.11.0 which has just been released.
Thanks!
