### ISSUE TITLE
Download fail

### ISSUE THREAD

**Issue by kitepea** [claudiodangelis/qrcp#280]
I'm opening this issue because:

- [ x] I have found a bug

Hello, I got the error:  ERR_CONNECTION_TIMED_OUT on window 10.
<img width="545" alt="image" src="https://github.com/claudiodangelis/qrcp/assets/64850687/65737285-4a78-4a96-bc8a-04bd27d65922">
![image](https://github.com/claudiodangelis/qrcp/assets/64850687/dc866db8-ebfe-4b42-963a-524a5cff3288)

**Comment by claudiodangelis** [comment]
Hello, apologies for the late reply.
Usually this may happen for two reasons:
1. The phone is not connected to the same wifi network of the laptop
2. The wifi network has some port filtering (i.e.: company networks very often have)

Does this ring any bell? Let me know if I can help you somehow.
Thanks!
C
