### ISSUE TITLE
show a website before downloading file

### ISSUE THREAD

**Issue by pokegamer5547** [claudiodangelis/qrcp#281]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

Chrome on android automatically starts downloading without showing anything, unless  the user tries to download again when it says "do you want to download file x again?"
It can confuse users so i think maybe showing a basic webpage ui when opening the link to share file. Similar to receiver option webpage.

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_
I Dont have go installed. Yeah, i used binary directly and it seems working fine for me.

**Comment by claudiodangelis** [comment]
Hello, thanks for raising this, will have a look at this in a couple weeks and come up with some idea.

Claudio

**Comment by claudiodangelis** [comment]
Hello, I will close this issue for now as I'm planning a full implementation of an "UI".
Thanks for taking the time to propose this!
Claudio
