### ISSUE TITLE
logo is not visible on website 

### ISSUE THREAD

**Issue by anjali29singh** [claudiodangelis/qrcp#282]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other
![Screenshot from 2023-06-18 14-51-13](https://github.com/claudiodangelis/qrcp/assets/94233830/054b9342-3359-46d9-9017-dc5eb5d3426f)

**Comment by claudiodangelis** [comment]
Thanks for reporting!
I will fix it once I'm back from holiday,
Claudio

**Comment by claudiodangelis** [comment]
Fixed in https://github.com/claudiodangelis/qrcp/commit/faa538904e98240440fc73e3ce09288514a07ddb, thanks!
