### ISSUE TITLE
add qrcp to winget

### ISSUE THREAD

**Issue by BOY0038v2** [claudiodangelis/qrcp#288]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

add qrcp to winget (windows package manager)

**Comment by claudiodangelis** [comment]
Hello, thanks for the proposal!
Unfortunately I'm not a Windows user so it would be nearly impossibile for me alone to do it.

Let's see if someone will stumble across this and will volunteer.

Thanks again,
Claudio

**Comment by vincenzoAiello** [comment]
Hello, in order to add qrpc to winget, is mandatory to have a windows installer (exe or msix) into the assets list. Actually there is only tar.gz file for windows. Once the windows installer will be added, I'll do the winget upload procedure.

BR
Vincenzo

**Comment by claudiodangelis** [comment]
Thanks for following up @vincenzoAiello. We use [goreleaser](https://github.com/goreleaser/goreleaser) for packaging the releases, and it apparently supports winget: [Winget - GoReleaser](https://goreleaser.com/customization/winget/).
I will do some research and post updates here, feel free to get involved if you want.
Thanks!
Claudio

**Comment by vincenzoAiello** [comment]
Hello @claudiodangelis , wow seems to be perfect.
What do you think about this?(obviously to be added to the .goreleaser.yml)

`# .goreleaser.yml
winget:
  - name: qrcp
    publisher: claudiodangelis
    license: MIT
    copyright: 2018 Claudio d'Angelis
    homepage: https://qrcp.sh/
    short_description:  Transfer files over wifi from your computer to your mobile device by scanning a QR code without leaving the terminal.
    repository:
      owner: claudiodangelis
      name: qrcp
      branch: main
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master`

**Comment by claudiodangelis** [comment]
Sounds pretty straightforward to me, though I'm not sure if an installer file is required or whose responsibility is to build it.
Let's keep investigating,
C

**Comment by claudiodangelis** [comment]
Hello, I think I will close this issue for now as it's been inactive for one year.
Hope to re-open it again later.
C

**Comment by claudiodangelis** [comment]
Hello @BOY0038v2 , @vincenzoAiello , qrcp is now availble on winget: https://github.com/microsoft/winget-pkgs/pull/239178

**Comment by BOY0038v2** [comment]
Great news! Thank you for adding it. I suggest you to add the winget method for installing qrcp on the [README](https://github.com/claudiodangelis/qrcp#installation)
