### ISSUE TITLE
Generate QR in terminal by right click on any file

### ISSUE THREAD

**Issue by oneofthehorses** [claudiodangelis/qrcp#303]
I'm opening this issue because:

- [ ] I have found a bug
- [+] I want to request a feature
- [+] I have a question
- [ ] Other

Hello! Thanks for your work! 

It would be awesome feature if after installing .deb package (or any other) new line in menu appears

What i mean: "right click" on any file in system - "qrcp qr code" and terminal shows up with ready QR code

Otherwise i needed open terminal each time and type all over again with path. Or how can i do if usuing Nemo file manager? 

Cheers!

**Comment by oneofthehorses** [comment]
I done it adding action to my Nemo window manager. Now i can generate qr code just by right click on any file. Can share it if you wish!

Topic can be closed

**Comment by claudiodangelis** [comment]
Hello, thanks for your effort on this! Please feel free to share your solution, I would be happy to add it to the documentation!

Claudio

**Comment by oneofthehorses** [comment]
**Step 1** Download this file [qrcp.nemo_action.txt](https://github.com/claudiodangelis/qrcp/files/13496738/qrcp.nemo_action.txt) and rename it to "qrcp.nemo_action". Place it to next direction ->
/home/YOUR_USER_NAME_HERE/.local/share/nemo/actions

**Step 2** Place this icon (if you wish) to your main theme folder. Mine is /usr/share/themes/Mint-Y-Aqua/cinnamon
![qrcp](https://github.com/claudiodangelis/qrcp/assets/151937835/5d1505ad-40fd-4741-a592-bf56e02aa22e)

**Step 3** Enjoy! And let me know if anything ain't works for you! :)

P.S. I would be really happy if someone can make GUI that can adopt easy to use HTTPS way of connection for "Normies" like me

**Comment by claudiodangelis** [comment]
This is fantastic!! Thanks for sharing, I'll find the right place on the website and will add it.
Thanks again!!

**Comment by claudiodangelis** [comment]
I will close this issue for now, I will add the above snippet somewhere in the documentation soon.
Thanks again for sharing this,
Claudio
