### ISSUE TITLE
文件后缀变化/file name ext-name changed??

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#305]
I'm opening this issue because:

[+] I have found a bug
windows终端扫描二维码，文件的时候，很多类型传输到手机上后，文件的后缀变成了txt（如exe，cmd）；一些类型文件能保留（如zip等）；

When the Windows terminal scans the QR code and files, after many types of files are transferred to the mobile phone, the suffix of the file becomes txt (such as exe, cmd); some types of files can be retained (such as zip, etc.)
How can I keep the original file name ext-name unchanged?

THX!!

**Comment by claudiodangelis** [comment]
Hello! The tool creates a zip archive only when sending more than one file per transfer.
Is this your case?

Thanks!
Claudio

**Comment by ilaoyao** [comment]
> Hello! The tool creates a zip archive only when sending more than one file per transfer. Is this your case?
> 
> Thanks! Claudio

no, when I try to transfered a single file from my windows PC (eg. d:\001\002.cmd), when I used a phone to scan the QR code and received a file name 002.txt). but it;s not all files will be like this. if the file's ext-name just like .zip, .iso,.pdf..., it will transfered with the orignal ext.
.cmd, .apk and some other's type will be changed to .txt automatic.

upload screentshot pics....
![00](https://github.com/claudiodangelis/qrcp/assets/12637485/080731fb-ce3a-4e2b-a7a0-02f628585168)
![11b53e99191c8e1c6a009907bb7721b](https://github.com/claudiodangelis/qrcp/assets/12637485/aff0e40b-d426-42ec-9028-6843fcf75c06)
![26c4ccd6056e96d61b80357dbe25d71](https://github.com/claudiodangelis/qrcp/assets/12637485/fe0c6f6e-09d8-411e-9e37-0334874b2878)



ps. multi-files and a folder will be created a zip-file, it's right!
at last. thx ur great job. it's amazing....

**Comment by ilaoyao** [comment]
> Hello! The tool creates a zip archive only when sending more than one file per transfer. Is this your case?
> 
> Thanks! Claudio

In addition, when I discussed this issue with my friends, we all agreed that this is set up for security reasons, such as unknown apk files are unknown risks to Android. But is it possible to add a parameter or a switch to set the file suffix not to be modified?

![002](https://github.com/claudiodangelis/qrcp/assets/12637485/1a329069-0bf1-4ac1-aedf-09504e6c7573)

ilaoyao

**Comment by claudiodangelis** [comment]
Ah, thanks for providing more context.
Yes, I would agree this is a security measure implemented by the browser.

Maybe you can add the `--zip` flag when sending, so once you receive the file you will just unzip it on the mobile, it should be smoother than replacing the extension manually.

Let me know if this helps, and thanks for the feedback!
C

**Comment by ilaoyao** [comment]
yes, --zip  flag can make  ot right, and i test this way already.

i just wonder, in your codes, i don't find any line about to change the send-file's ext-name change to .txt, only in  page.go i can see your code add .txt to non-ext-name file.

sincerely
ilaoyao

**Comment by claudiodangelis** [comment]
Hello, I will close this issue for now as this is not something we have control over.
Thanks for reporting!
