### ISSUE TITLE
How to create contextmenu of any file to show qrcode in Mac？？

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#306]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [x] Other

How to create contextmenu of any file to show qrcode in Mac？？

- My Go version is: _(paste the output of `go version` and remember that qrcp requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_

**Comment by claudiodangelis** [comment]
Hello, this would be a very cool feature, but at this time I don't have a solution for it.

Let's see, maybe other users have found a nice solution and will post it here.

Thanks for the nice suggestion!
Claudio

**Comment by ilaoyao** [comment]
I tried to use Mac OS  Automator, add shell script to built it,  when executed through the context menu of any file,  it can open the terminal normally, but the subsequent qcrp /path/filename.ext command cannot succeed.

i used one app named easyshare for mac, it can show a qrcode by click MacOS's sevices context menu.

thx u reply.
ilaoyao

**Comment by claudiodangelis** [comment]
Ah, interesting. Do you mind sharing the Automator code here? Maybe we can have a look together, thanks!

**Comment by ilaoyao** [comment]
> Ah, interesting. Do you mind sharing the Automator code here? Maybe we can have a look together, thanks!

Automator --> quick action --> run shell script --> files & folders , Finder , and pasted the scropt blow:

`
for f in "$@"
do
    open -a "Terminal" "/user/my/qrcp/qrcp" "$f"
done
`
/user/my/qrcp/qrcp is the qrcp bin-file.

save as qrcpopen name and choose a file or folder right click, and choose the qrcpopen name, the terminal open, but pop a windows says: qrcp need at least one arg....ect.

so i failed.   :-(

**Comment by claudiodangelis** [comment]
Ok, very good!
Can we close this issue now?
Thanks!!
