### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#309]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

https://www.52pojie.cn/forum.php?mod=redirect&goto=findpost&ptid=1865497&pid=48852802
https://www.52pojie.cn/forum.php?mod=redirect&goto=findpost&ptid=1865497&pid=48852814
https://www.52pojie.cn/forum.php?mod=redirect&goto=findpost&ptid=1865497&pid=48856225

one of my friend test this app, Encountered something abnormal. Any idea?

**Comment by claudiodangelis** [comment]
Hello, thanks for reporting! The website requires a login, and also, I can't really read Chinese !

Could you please summarize it here in English?

Thanks!
