### ISSUE TITLE
New Bug to show the QRcode in CMD (old verison)

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#311]
I'm opening this issue because:
- [x] I have found a bug

OS: **Windows 23H2**
qrcp version: **0.11.0**

In fact, this bug existed from the beginning, the cause has been analyzed, and there also have a  temporary solutions:

**Situation description**
1. Use the old version of cmd to open the QR code (not  Windows Terminal, but a cmd console like win7)
2. The generated QR code will be deformed and cannot be recognized when scanned with a mobile phone.

**Temporary solution**
1. The temporary solution is: **chcp 437**, modify the code page and replace it with a consolas mono font eg. **Consola**. At this time, the QR code will be displayed correctly.
2. Because the cmd code page of the Chinese system is **936**, the **Consola** font cannot be replaced under 936. just like **Simsun** or **Simhei**

**Disadvantages of temporary solutions**
After passing **chcp 437**, some script files with Chinese content will generate garbled characters when running. Although it can be restored through **chcp 936**,  but it is cumbersome.

So I would like to ask if there is a solution to this situation (under Chinese windows system)

**screenshot:**
![001](https://github.com/claudiodangelis/qrcp/assets/12637485/2f453634-c82c-41b5-aeb6-5da3453c4a4c)
![002](https://github.com/claudiodangelis/qrcp/assets/12637485/b6406d8b-fe0f-4012-93ce-645a94478f2e)

**Comment by claudiodangelis** [comment]
Hello, unfortunately there is very little we can do for this.
Did you try passing the `--browser` flag? This flag will open a browser tab and display the QR as an image.
Let me know if this helps, thanks!

Claudio

**Comment by ilaoyao** [comment]
The --browser parameter is effective.
But what I am talking about should be caused by the system console code page, especially in some countries in Asia, like China where I am.
Maybe this is an innate problem with MS cmd.

I will close this issue.
thank you for your reply.

ilaoyao
