### ISSUE TITLE
QRcode show in a single windows?

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#313]
I'm opening this issue because:

- [x] I want to request a feature

Hi, it's me again!

i have a idea, is any possible to handle the qrcode  by this way?
like what i said, in asian language's windows, cmd have a issue with a codepage, it perhaps makes a wrong qrcode show.
can it show the qrcode with a single windows without cmd-line?
or pop a windows only include a qrcode picture？
just like the pic blow:

![ly_231210_122446](https://github.com/claudiodangelis/qrcp/assets/12637485/376a3d49-1b8c-46cf-892a-5afabf31b554)

sincerely.
ilaoyao

**Comment by claudiodangelis** [comment]
Hello! At this time this is not possible, but it will be the next thing I will work on.

Thanks!
C
