### ISSUE TITLE
Finish file transferring , QRCP not exit？？？

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#314]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [x] I have a question
- [ ] Other
- [ ] 
I seem to remember that in version 0.10.1, after scanning the QR code and transferring, the terminal will automatically end and back to prompt. Now in version 0.11.0, the cursor is still blinking after  transferring finished. Is this revised in new version? Or is the memory wrong?

**Comment by claudiodangelis** [comment]
Hello, I cannot reproduce this issue, the transfer completes successfully.
If this is not a bug, the only reason why it could remain open is that you passed the `--keep-alive` (or `-k`) flag.

Thanks for reporting!

**Comment by ilaoyao** [comment]
> Hello, I cannot reproduce this issue, the transfer completes successfully. If this is not a bug, the only reason why it could remain open is that you passed the `--keep-alive` (or `-k`) flag.
> 
> Thanks for reporting!

Yes! I just found that i used a flag -k in cmd file.
sorry. my mistake!

ilaoyao
