### ISSUE TITLE
Can Qrcp run with a log file?

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#316]
I'm opening this issue because:

- [ ] I have found a bug
- [ ] I want to request a feature
- [x] I have a question
- [ ] Other

Is there a FLAG like -log that can create a log file in the %temp%-folder, when qrcp is running ?
in the log file we can see the url address..

**Comment by claudiodangelis** [comment]
Hello! There is no such flag yet, honestly I'm not sure how much valuable it would be in general terms.
Do you have any specific usecase for this? (i.e.: debugging, etc?)

Thanks for your continued support!
Claudio

**Comment by ilaoyao** [comment]
yes, I want to make a GUI-windows to show the qrcode, not in a cmd-windows, i just want the current qrcd-cmd url.
eg. if the qrcp.exe is running, then i can hide the cmd-windows,  instead of a GUI window, but i need a current url address to show on this gui windows.

so can it create a log-file in temp folder, file-name is just like qrcp-PID.txt. and write the current url address in this file, so i can read the url-address from this file. so i can hide the cmd-windows and show the gui-windows,just like blow:

![111](https://github.com/claudiodangelis/qrcp/assets/12637485/0ad95aba-fcb8-463b-98fd-909a72dc6f00)


even more, can create a png file with transparent backgound,so can show the qrcode in the gui.

sincerely
ilaoyao

**Comment by claudiodangelis** [comment]
Hello, knowing your IP, you could try passing the `--path` and `--port` flags to make the URL predictible:

```
qrcp --path file --port 8080 /yourfile.txt
```

The resulting URL will be:
```
http://<your IP>:8080/send/file
```

Let me know if this helps, thanks!
