### ISSUE TITLE
zip flag have a bug

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#317]
I'm opening this issue because:
- [x] I have found a bug

**qrcp folder** will zip the current folder and transfer to the mobile.but with qrcp ver 0.11.0, I found a bug like:

# A. conclusion
- Ver 0.11.0, zip have some bugs
- Ver 0.10.1, zip everything is fine

# B. Scene reenactment

## 1) if the folder is the Same level directory

![11](https://github.com/claudiodangelis/qrcp/assets/12637485/0f6a0a3d-5abf-4681-922f-b3fdb390e1b9)

when i ran **qrcp ..\333**, then i used my phone to scan this , transfer was right, but the zip-file will look like blow( i user alzip app), it has been insert a sub-folder name **__** :
![Screenshot_2023-12-16-09-12-23-772_com estsoft alzip_看图王](https://github.com/claudiodangelis/qrcp/assets/12637485/0b90ed63-fb11-498c-88a6-48da457c528a)
but it can be  extracted  normally.

when i use the rootexplore app to extract it, RE app show error!
![Screenshot_2023-12-16-09-12-43-121_com speedsoftware rootexplorer_看图王](https://github.com/claudiodangelis/qrcp/assets/12637485/a0f4bfd9-fbdd-44c6-98dd-5316168462f0)
![Screenshot_2023-12-16-09-12-56-019_com speedsoftware rootexplorer_看图王](https://github.com/claudiodangelis/qrcp/assets/12637485/26d35ae6-d804-4f56-bb21-9718a1ce8f60)

when i send this zip file back to my computer, and i extract it with 7-Zip, it look blow:
![231](https://github.com/claudiodangelis/qrcp/assets/12637485/cddfc220-2baa-4c87-a03a-0fcfd6e6b190)

the folder and the filename has been changed all.

## 2)if the folder is a sub directory

![222](https://github.com/claudiodangelis/qrcp/assets/12637485/d7f21817-f011-4f08-a325-8d06621ff933)

when i ran **qrcp 333**, then i used my phone to scan this , transfer was right, and the alzip app work right.

when i use the rootexplore app to extract it, RE app show error again!
![Screenshot_2023-12-16-09-17-57-746_com speedsoftware rootexplorer_看图王](https://github.com/claudiodangelis/qrcp/assets/12637485/ca2a98e2-c6bf-48fe-a14f-c74f227fb7c7)

![Screenshot_2023-12-16-09-18-06-824_com speedsoftware rootexplorer_看图王](https://github.com/claudiodangelis/qrcp/assets/12637485/4cdc0c2f-3463-4cfc-a2db-3bed22407896)

when i send this zip file back to my computer, and i extract it with 7-Zip, it look blow:
![333](https://github.com/claudiodangelis/qrcp/assets/12637485/8397d83d-60fb-4742-9c44-dff608651491)

the folder and the filename has been changed all.

## I run the version 0.10.1 and it works all fine, and all the errors above are not exist and the structure of the folders shows all correctly.

**Comment by claudiodangelis** [comment]
Hello @ilaoyao , a new version is out `0.11.1` and it will solve the issue you are experiencing.
Thanks a lot for reporting the issue and thanks to @vincenzoAiello for fixing it right away!

Please let me know if we can close this issue.
