### ISSUE TITLE
Not Support X86 Platform？

### ISSUE THREAD

**Issue by ilaoyao** [claudiodangelis/qrcp#319]
I'm opening this issue because:

- [] I have found a bug
- [ ] I want to request a feature
- [x] I have a question
- [ ] Other

one of my friend test the qrcp in windows 7 x86, But it can't work.
Don't qrcp support the x86 windows platform?

**Comment by claudiodangelis** [comment]
Hello, since Windows 7 is no longer maintained, I guess there should be no point continuing supporting it.
Maybe you can try building it from the source code and see if it works.

I will close this issue for now, please feel free to re-open it if you need more assistence.

Thanks!
