### ISSUE TITLE
Missing MacOS binaries for few latest releases

### ISSUE THREAD

**Issue by GitSparTV** [claudiodangelis/qrcp#329]
Hi. I noticed that last releases mention MacOS packages, but they don't exist for these releases.
[0.10.1](https://github.com/claudiodangelis/qrcp/releases/tag/0.10.1) is the latest release with MacOS binaries. Newer ones don't have them.

**Comment by claudiodangelis** [comment]
Hello, sorry for the huge delay.
You're right, there is something wrong in the "Downloads" section of the release page, MacOS binaries links are broken! Thanks for spotting.

However, you can still find it in the "assets" section, for example: https://github.com/claudiodangelis/qrcp/releases/download/0.11.3/qrcp_0.11.3_darwin_amd64.tar.gz

Hope this helps,
Claudio
