### ISSUE TITLE
Missing versions on pkg.go.dev

### ISSUE THREAD

**Issue by simonhammes** [claudiodangelis/qrcp#336]
https://pkg.go.dev/github.com/claudiodangelis/qrcp does not contain qrcp's releases.

As a result, `go install github.com/claudiodangelis/qrcp@latest` (from the `README`) does not install the latest release, but a development build instead. This can be confirmed by running `qrcp version`.

**Comment by claudiodangelis** [comment]
I overlooked this, good catch, thanks!
I'm going to take care of it in the next few weeks. Thanks for taking the time for reporting,
C

**Comment by simonhammes** [comment]
Thanks for the quick reply, and no worries :slightly_smiling_face:

**Comment by claudiodangelis** [comment]
It seems that this is due to the missing "v" prefix on the github releases.
Very good catch! I'll review the release process to make sure everything works well.
Thanks again for taking the time for reporting this.
C
