### ISSUE TITLE
Add folder selector when receiving

### ISSUE THREAD

**Issue by simonhughxyz** [claudiodangelis/qrcp#337]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

It would be nice to be able to select folders as well as files when using `qrcp receive`, at the moment you can select files, but sometimes I need to upload a entire folder recursively.

**Comment by claudiodangelis** [comment]
Hello, sorry for the late reply. At the moment this is nearly impossible to implement due to the minimalistic "front end" web application which is used for choosing the files.
I will keep this in mind for the future.
Thanks,
Claudio

**Comment by claudiodangelis** [comment]
I will close this for now, since, as stated, there is no plan for this at the moment due to the technical limitation of the frontend.
