### ISSUE TITLE
Feature request: Add support for 3rd-party file hosts

### ISSUE THREAD

**Issue by benvaljean** [claudiodangelis/qrcp#42]
It would be great if instead of hosting the file it could be auto uploading to a file sharing host. 

https://www.file.io/  has an API that is free.

**Comment by claudiodangelis** [comment]
Hi, mm, I'm not sure I understand this feature: you mean that something like: 

```
qr-filetransfer ./myfile.pdf
```

causes myfile.pdf to be uploaded to file.io?

**Comment by benvaljean** [comment]
Yes, thats correct. The file.io url is then used to create the QR code.

**Comment by claudiodangelis** [comment]
Got it, but what I don't understand is: what would be the benefit of uploading to the cloud and then downloading from the cloud rather than directly transfering from desktop to mobile?

**Comment by benvaljean** [comment]
You can transfer files without needing to be on the same network. For
instance when using a remote host, or when the wifi network has layer 2
routing disabled.

**Comment by claudiodangelis** [comment]
Ok thanks, now it's clear. I was already thinking about adding a `remote` (or `external`) flag to lift the same-network restriction (for example: you want to transfer files from a remote host connected via ssh); my idea was to bound the server to the external IP in that case, but that would make an HTTPS connection mandatory.

Using a file sharing host as a middleware is a pretty good solution, many thanks for coming up with this, I'm researching.

**Comment by claudiodangelis** [comment]
Cross-reference: https://github.com/claudiodangelis/qrcp/issues/97
