### ISSUE TITLE
Allow binding to publicly accessible interfaces too

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/qrcp#68]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

**Comment by styfle** [comment]
Could [ngrok](https://ngrok.com) be utilized here?

**Comment by claudiodangelis** [comment]
@styfle sorry for late reply, I'm not 100% sure ngrok could be a solution here.

However, I would put this issue on hold until #24 (support for HTTPS) is implemented.

**Comment by claudiodangelis** [comment]
This was implemented as part of the latest major refactoring.
Just use the `--interface=any` special interface, and it will bind to `0.0.0.0`. The displayed URL will be the external IP of the host, unless the `--fdqn` argument is passed; in that case, the fully-qualified domain name is displayed instead.

```sh
qrcp send -i any  /path/to/file
```
