### ISSUE TITLE
zip.AddFile undefined when running "go get github.com/claudiodangelis/qr-filetransfer"

### ISSUE THREAD

**Issue by issmirnov** [claudiodangelis/qrcp#70]
I'm opening this issue because:

- [X] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

I am trying to install the binary with `go get github.com/claudiodangelis/qr-filetransfer`, and getting the following error:

```
/Users/issmirnov/go/github.com/claudiodangelis/qr-filetransfer/content.go:54:7: zip.AddFile undefined (type *archivex.ZipFile has no field or method AddFile)
```

It is coming from [here](https://github.com/claudiodangelis/qr-filetransfer/blob/master/content.go#L54).

I have reproduced this on two systems: ubuntu and OSX.

OSX:
```
$ go version
go version go1.10.3 darwin/amd64

$ echo $GOPATH
/Users/issmirnov/go

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88
```

Ubuntu:
```
$ go version
go version go1.9.4 linux/amd64

$ echo $GOPATH
/Users/issmirnov/go

$ uname -r
Linux mysecrethostname 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ $ cat /etc/lsb-release                     
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LT
```

**Comment by issmirnov** [comment]
I believe the cause of this bug is this commit: https://github.com/jhoonb/archivex/commit/1eb6e91aa0b4b9b1623fdf3a2a38142b4afe4b63

It removes the `AddFile` method, and replaces it with `Add`.

**Comment by claudiodangelis** [comment]
Thanks for reporting @issmirnov, I will look at it ASAP

**Comment by vizzah** [comment]
Having the same issue with the current version:

$ go get github.com/claudiodangelis/qrcp
# github.com/claudiodangelis/qrcp/util
dev/go/src/github.com/claudiodangelis/qrcp/util/util.go:38:7: zip.AddFile undefined (type *archivex.ZipFile has no field or method AddFile)

**Comment by claudiodangelis** [comment]
Hi @vizzah, sorry to hear, which version of go are you using?

**Comment by Maijin** [comment]
Same issue here "go version go1.14.2 darwin/amd64"

**Comment by vizzah** [comment]
> Hi @vizzah, sorry to hear, which version of go are you using?

go version go1.12.8 linux/amd64

thanks

**Comment by edmooney** [comment]
Same issue on: go version go1.14.2 linux/amd64
Thank you!

**Comment by u-0000** [comment]
Same issue on go version go1.14.2 android/arm64

**Comment by beppu** [comment]
I get this error too with go version go1.13 linux/amd64 .  However, if I clone the repo and do `go build`, it builds successfully, and `qrcp` seems to work.

**Comment by claudiodangelis** [comment]
Should be all good now, the issue was the one pointed out by @issmirnov, which I totally forgot about.

Please let me know if everything works as expected, and thanks everyone for taking the time to report the problem.

**Comment by Maijin** [comment]
Awesome works like a charm now
