### ISSUE TITLE
Add sending a string

### ISSUE THREAD

**Issue by Gavinok** [claudiodangelis/qrcp#88]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: go1.13.7 linux/amd64
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: /home/gavinok/go:/home/gavinok/Programming/go

**Comment by claudiodangelis** [comment]
Could you please describe an example usecase for this feature? 
Thanks

**Comment by Gavinok** [comment]
Sorry didn't realize that I had submitted this. Currently if you want to send a string using the qrcode from your phone using -receive you need to create a text file on your phone containing the text to be sent. 

- The feature I was hoping to have added is the ability to just send the string from my phone.

One way I had in mind was to add a text box on the file transfer page that can then be either saved to the directory specified by -receive. A second way I had in mind was to allow receive to specify a file that the text can be stored in when calling -receive. The final idea I had was to simply print it out to the original terminal. I think the first 2 allow for more extensibility.

**Comment by claudiodangelis** [comment]
Hi @Gavinok, well, it looks like something useful enough to be implemented.

Thanks!

**Comment by faxm0dem** [comment]
if the file to send is smaller than 1k it could encode it into the QR-code directly no need for a webserver ;-)

**Comment by PauloRSF** [comment]
Can i take this one?

**Comment by claudiodangelis** [comment]
> if the file to send is smaller than 1k it could encode it into the QR-code directly no need for a webserver ;-)

@faxm0dem agreed, but that is only true for "laptop > mobile" transfers but not from the other way around, which I think is the actual use case that this feature would cover. I'm thinking about transferring copied text from a message, URLs, etc.

**Comment by claudiodangelis** [comment]
> Can i take this one?

@PauloRSF, yes, absolutely.

Before getting started, let's discuss what the best implemention would be. I'm thinking about these specs:
- the upload pages has both a "Upload file" and a "Title Input + Text Textarea" features
- (?) features are mutually exclusive
- if the title is not set, qrcp assigns one following a given pattern (i.e.: `qrcp-text-file-${date}.txt`)
- the transferred file has a  text/plain MIME type
- ".txt" is appended to the title
- the resulting txt file is POST'd to `/receive/{random}` as if it was a regularly uploaded file

What do you think? Thanks for proposing!

**Comment by PauloRSF** [comment]
Sounds good to me! Although, i believe there's no need to make the features mutually exclusive. It really would be odd for someone to want to transfer some plain text and files at the same time, but, if someone wants to, why not? Do you agree?

**Comment by claudiodangelis** [comment]
@PauloRSF you are right, agreed 🤝

**Comment by claudiodangelis** [comment]
@Gavinok this is implemented now and available as of version 0.6.0, thanks for proposing!
