### ISSUE TITLE
macOS 10.15.2  exec format error: qrcp

### ISSUE THREAD

**Issue by Crazy-MT** [claudiodangelis/qrcp#94]

**Comment by m1nka** [comment]
Had the same issue. You need to install it using `go get github.com/claudiodangelis/qrcp`.

**Comment by claudiodangelis** [comment]
Sorry for that, I know where the problem is.

Please install it with "go get" as suggested, I will fix that in a few
days.

Thanks!

Il mer 22 apr 2020, 14:46 maxj <notifications@github.com> ha scritto:

**Comment by latel** [comment]
I install with "go get", but no luck, qcrp is not installed

```
$ go get github.com/claudiodangelis/qrcp
$ qrcp
zsh: command not found: qrcp
```

**Comment by Crazy-MT** [comment]
> I install with "go get", but no luck, qcrp is not installed
> 
> ```
> $ go get github.com/claudiodangelis/qrcp
> $ qrcp
> zsh: command not found: qrcp
> ```

+1

**Comment by claudiodangelis** [comment]
Hello, I fixed the problem. MacOS releases are now available in the Releases page.

You should be able to install it by running:
```sh
# This, or manually download it from the Releases page
wget https://github.com/claudiodangelis/qrcp/releases/download/0.5.3/qrcp_0.5.3_macOS_x86_64.tar.gz
# Extract the binary
tar xf qrcp_0.5.3_macOS_x86_64.tar.gz
# Copy the binary to /usr/local/bin
sudo cp qrcp /usr/loca/bin
# Set execution permissions
sudo chmod +x /usr/local/bin
# Test if it works
qrcp --help
```

Please let me know if this fixed the problem, thanks for your patience!

**Comment by michaellee123** [comment]
You can try this:You can try this:https://github.com/michaellee123/EasyShare
