### ISSUE TITLE
can't install in macos with go 1.12

### ISSUE THREAD

**Issue by nvthuong1996** [claudiodangelis/qrcp#96]
### i can't install package please see
i can try use sudo when install but it not working.
![enter image description here](https://www.upsieutoc.com/images/2020/04/22/Screen-Shot-2020-04-22-at-11.12.59-PM.png)

**Comment by nvthuong1996** [comment]
sorry i lose step install

**Comment by michaellee123** [comment]
You can try this:You can try this:https://github.com/michaellee123/EasyShare
