### ISSUE TITLE
Add AUR package to README

### ISSUE THREAD

**Issue by thiagoalmeidasa** [claudiodangelis/qrcp#98]
I'm opening this issue because:

- [x ] Other
Archlinux package created at https://aur.archlinux.org/packages/qrcp-bin/

**Comment by claudiodangelis** [comment]
That's great @thiagoalmeidasa! I am an Arch user too!

Just for your information, qrcp used to be called qr-filetransfer, and a package does exist on AUR for that: https://aur.archlinux.org/packages/qr-filetransfer-git/

However, it's an "-git" package, so if the qr-filetransfer-git will be renamed to qrcp-git, please make sure to list it as a conflicting package. I will make the author of that package aware of the same.

I will now edit the title of this issue to "Add AUR package to README".

Thank you again for taking the time to package this tool.

**Comment by thiagoalmeidasa** [comment]
Just did. Thanks, man.

**Comment by claudiodangelis** [comment]
@thiagoalmeidasa  FYI I just spotted this package: https://aur.archlinux.org/packages/qrcp/

**Comment by claudiodangelis** [comment]
Hello @thiagoalmeidasa , I added a release automation. Please update the PKGBUILD to use the following URL for the download :

https://github.com/claudiodangelis/qrcp/releases/download/0.5.3/qrcp_0.5.3_linux_x86_64.tar.gz

Also, this is a tar.gz package so it should be unpacked when installing it. 

Thank you!
